// Code generated by protoc-gen-go.
// source: surface.proto
// DO NOT EDIT!

/*
Package gnostic_surface_v1 is a generated protocol buffer package.

It is generated from these files:
	surface.proto

It has these top-level messages:
	Field
	Type
	Method
	Model
*/
package gnostic_surface_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FieldKind int32

const (
	FieldKind_SCALAR    FieldKind = 0
	FieldKind_MAP       FieldKind = 1
	FieldKind_ARRAY     FieldKind = 2
	FieldKind_REFERENCE FieldKind = 3
)

var FieldKind_name = map[int32]string{
	0: "SCALAR",
	1: "MAP",
	2: "ARRAY",
	3: "REFERENCE",
}
var FieldKind_value = map[string]int32{
	"SCALAR":    0,
	"MAP":       1,
	"ARRAY":     2,
	"REFERENCE": 3,
}

func (x FieldKind) String() string {
	return proto.EnumName(FieldKind_name, int32(x))
}
func (FieldKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TypeKind int32

const (
	TypeKind_STRUCT TypeKind = 0
	TypeKind_OBJECT TypeKind = 1
)

var TypeKind_name = map[int32]string{
	0: "STRUCT",
	1: "OBJECT",
}
var TypeKind_value = map[string]int32{
	"STRUCT": 0,
	"OBJECT": 1,
}

func (x TypeKind) String() string {
	return proto.EnumName(TypeKind_name, int32(x))
}
func (TypeKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Position int32

const (
	Position_BODY     Position = 0
	Position_HEADER   Position = 1
	Position_FORMDATA Position = 2
	Position_QUERY    Position = 3
	Position_PATH     Position = 4
)

var Position_name = map[int32]string{
	0: "BODY",
	1: "HEADER",
	2: "FORMDATA",
	3: "QUERY",
	4: "PATH",
}
var Position_value = map[string]int32{
	"BODY":     0,
	"HEADER":   1,
	"FORMDATA": 2,
	"QUERY":    3,
	"PATH":     4,
}

func (x Position) String() string {
	return proto.EnumName(Position_name, int32(x))
}
func (Position) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Field is a field in a definition and can be associated with
// a position in a request structure.
type Field struct {
	Name          string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type          string    `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Kind          FieldKind `protobuf:"varint,3,opt,name=kind,enum=gnostic.surface.v1.FieldKind" json:"kind,omitempty"`
	Format        string    `protobuf:"bytes,4,opt,name=format" json:"format,omitempty"`
	Position      Position  `protobuf:"varint,5,opt,name=position,enum=gnostic.surface.v1.Position" json:"position,omitempty"`
	NativeType    string    `protobuf:"bytes,6,opt,name=nativeType" json:"nativeType,omitempty"`
	FieldName     string    `protobuf:"bytes,7,opt,name=fieldName" json:"fieldName,omitempty"`
	ParameterName string    `protobuf:"bytes,8,opt,name=parameterName" json:"parameterName,omitempty"`
	Serialize     bool      `protobuf:"varint,9,opt,name=serialize" json:"serialize,omitempty"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Field) GetKind() FieldKind {
	if m != nil {
		return m.Kind
	}
	return FieldKind_SCALAR
}

func (m *Field) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Field) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position_BODY
}

func (m *Field) GetNativeType() string {
	if m != nil {
		return m.NativeType
	}
	return ""
}

func (m *Field) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Field) GetParameterName() string {
	if m != nil {
		return m.ParameterName
	}
	return ""
}

func (m *Field) GetSerialize() bool {
	if m != nil {
		return m.Serialize
	}
	return false
}

// Type typically corresponds to a definition, parameter, or response
// in an API and is represented by a type in generated code.
type Type struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind        TypeKind `protobuf:"varint,2,opt,name=kind,enum=gnostic.surface.v1.TypeKind" json:"kind,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ContentType string   `protobuf:"bytes,4,opt,name=contentType" json:"contentType,omitempty"`
	Fields      []*Field `protobuf:"bytes,5,rep,name=fields" json:"fields,omitempty"`
	TypeName    string   `protobuf:"bytes,6,opt,name=typeName" json:"typeName,omitempty"`
}

func (m *Type) Reset()                    { *m = Type{} }
func (m *Type) String() string            { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()               {}
func (*Type) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetKind() TypeKind {
	if m != nil {
		return m.Kind
	}
	return TypeKind_STRUCT
}

func (m *Type) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Type) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Type) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Type) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

// Method is an operation of an API and typically has associated client and server code.
type Method struct {
	Operation          string `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	Path               string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Method             string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Description        string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Name               string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	HandlerName        string `protobuf:"bytes,6,opt,name=handlerName" json:"handlerName,omitempty"`
	ProcessorName      string `protobuf:"bytes,7,opt,name=processorName" json:"processorName,omitempty"`
	ClientName         string `protobuf:"bytes,8,opt,name=clientName" json:"clientName,omitempty"`
	ParametersTypeName string `protobuf:"bytes,9,opt,name=parametersTypeName" json:"parametersTypeName,omitempty"`
	ResponsesTypeName  string `protobuf:"bytes,10,opt,name=responsesTypeName" json:"responsesTypeName,omitempty"`
}

func (m *Method) Reset()                    { *m = Method{} }
func (m *Method) String() string            { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()               {}
func (*Method) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Method) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Method) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Method) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Method) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetHandlerName() string {
	if m != nil {
		return m.HandlerName
	}
	return ""
}

func (m *Method) GetProcessorName() string {
	if m != nil {
		return m.ProcessorName
	}
	return ""
}

func (m *Method) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *Method) GetParametersTypeName() string {
	if m != nil {
		return m.ParametersTypeName
	}
	return ""
}

func (m *Method) GetResponsesTypeName() string {
	if m != nil {
		return m.ResponsesTypeName
	}
	return ""
}

// Model represents an API for code generation.
type Model struct {
	Name    string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Types   []*Type   `protobuf:"bytes,2,rep,name=types" json:"types,omitempty"`
	Methods []*Method `protobuf:"bytes,3,rep,name=methods" json:"methods,omitempty"`
}

func (m *Model) Reset()                    { *m = Model{} }
func (m *Model) String() string            { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()               {}
func (*Model) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Model) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func init() {
	proto.RegisterType((*Field)(nil), "gnostic.surface.v1.Field")
	proto.RegisterType((*Type)(nil), "gnostic.surface.v1.Type")
	proto.RegisterType((*Method)(nil), "gnostic.surface.v1.Method")
	proto.RegisterType((*Model)(nil), "gnostic.surface.v1.Model")
	proto.RegisterEnum("gnostic.surface.v1.FieldKind", FieldKind_name, FieldKind_value)
	proto.RegisterEnum("gnostic.surface.v1.TypeKind", TypeKind_name, TypeKind_value)
	proto.RegisterEnum("gnostic.surface.v1.Position", Position_name, Position_value)
}

func init() { proto.RegisterFile("surface.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0x7f, 0x6b, 0xdf, 0x7e, 0xfd, 0x64, 0x66, 0x81, 0x4c, 0x55, 0x90, 0x15, 0xb1, 0x88,
	0x2a, 0x64, 0xd1, 0xc2, 0x02, 0xb1, 0x73, 0x53, 0x57, 0x15, 0x90, 0x26, 0x0c, 0xee, 0x22, 0x4b,
	0x63, 0x4f, 0x88, 0x45, 0xe2, 0xb1, 0x3c, 0x43, 0x25, 0xd8, 0xf1, 0x52, 0x3c, 0x06, 0xaf, 0xc0,
	0xab, 0xa0, 0xb9, 0xb6, 0x13, 0x97, 0x24, 0xbb, 0x99, 0x33, 0xe7, 0x5e, 0xcf, 0x39, 0xe7, 0x8e,
	0xe1, 0x58, 0x7c, 0xab, 0xe7, 0x69, 0xc6, 0xc2, 0xaa, 0xe6, 0x92, 0x13, 0xf2, 0xa5, 0xe4, 0x42,
	0x16, 0x59, 0xd8, 0xc1, 0xf7, 0xe7, 0x83, 0x5f, 0x3a, 0x58, 0xd7, 0x05, 0x5b, 0xe6, 0x84, 0x80,
	0x59, 0xa6, 0x2b, 0xe6, 0x6b, 0x81, 0x36, 0x74, 0x29, 0xae, 0x15, 0x26, 0xbf, 0x57, 0xcc, 0xd7,
	0x1b, 0x4c, 0xad, 0xc9, 0x39, 0x98, 0x5f, 0x8b, 0x32, 0xf7, 0x8d, 0x40, 0x1b, 0xfe, 0x7f, 0xf1,
	0x34, 0xdc, 0x6e, 0x1a, 0x62, 0xc3, 0xf7, 0x45, 0x99, 0x53, 0xa4, 0x92, 0xc7, 0x60, 0xcf, 0x79,
	0xbd, 0x4a, 0xa5, 0x6f, 0x62, 0xa3, 0x76, 0x47, 0xde, 0x80, 0x53, 0x71, 0x51, 0xc8, 0x82, 0x97,
	0xbe, 0x85, 0xed, 0x4e, 0x77, 0xb5, 0x9b, 0xb6, 0x1c, 0xba, 0x66, 0x93, 0x67, 0x00, 0x65, 0x2a,
	0x8b, 0x7b, 0x96, 0xa8, 0xeb, 0xd9, 0xd8, 0xb5, 0x87, 0x90, 0x53, 0x70, 0xe7, 0xea, 0x12, 0xb7,
	0x4a, 0xd1, 0x21, 0x1e, 0x6f, 0x00, 0xf2, 0x1c, 0x8e, 0xab, 0xb4, 0x4e, 0x57, 0x4c, 0xb2, 0x1a,
	0x19, 0x0e, 0x32, 0x1e, 0x82, 0xaa, 0x87, 0x60, 0x75, 0x91, 0x2e, 0x8b, 0x1f, 0xcc, 0x77, 0x03,
	0x6d, 0xe8, 0xd0, 0x0d, 0x30, 0xf8, 0xa3, 0x81, 0x89, 0x9f, 0xda, 0xe5, 0xdb, 0xcb, 0xd6, 0x23,
	0x7d, 0xbf, 0x28, 0x55, 0xdb, 0xb3, 0x28, 0x80, 0xa3, 0x9c, 0x89, 0xac, 0x2e, 0x2a, 0x74, 0xc3,
	0xc0, 0x66, 0x7d, 0x48, 0x31, 0x32, 0x5e, 0x4a, 0x56, 0x4a, 0xd4, 0xdc, 0x38, 0xd9, 0x87, 0xc8,
	0x39, 0xd8, 0xa8, 0x51, 0xf8, 0x56, 0x60, 0x0c, 0x8f, 0x2e, 0x9e, 0xec, 0xcd, 0x86, 0xb6, 0x44,
	0x72, 0x02, 0x8e, 0x0a, 0x15, 0x4d, 0x68, 0x5c, 0x5c, 0xef, 0x07, 0xbf, 0x75, 0xb0, 0xc7, 0x4c,
	0x2e, 0x78, 0xae, 0xac, 0xe0, 0x15, 0xab, 0x53, 0xbc, 0x5b, 0x23, 0x74, 0x03, 0x28, 0x07, 0xaa,
	0x54, 0x2e, 0xba, 0x29, 0x51, 0x6b, 0x15, 0xf9, 0x0a, 0x6b, 0x5b, 0x29, 0xed, 0xee, 0x5f, 0x9d,
	0xe6, 0xb6, 0xce, 0xce, 0x4f, 0xab, 0xe7, 0x67, 0x00, 0x47, 0x8b, 0xb4, 0xcc, 0x97, 0x6d, 0x5c,
	0xcd, 0x4d, 0xfb, 0x10, 0x46, 0x5a, 0xf3, 0x8c, 0x09, 0xc1, 0xeb, 0x5e, 0xe8, 0x0f, 0x41, 0x35,
	0x36, 0xd9, 0xb2, 0x60, 0xa5, 0xec, 0xa5, 0xde, 0x43, 0x48, 0x08, 0x64, 0x3d, 0x03, 0x22, 0xe9,
	0x8c, 0x71, 0x91, 0xb7, 0xe3, 0x84, 0xbc, 0x80, 0x47, 0x35, 0x13, 0x15, 0x2f, 0x05, 0xdb, 0xd0,
	0x01, 0xe9, 0xdb, 0x07, 0x83, 0x9f, 0x1a, 0x58, 0x63, 0x9e, 0xb3, 0xe5, 0xce, 0x99, 0x09, 0xc1,
	0x52, 0xd6, 0x0b, 0x5f, 0xc7, 0xf0, 0xfc, 0x7d, 0x43, 0x43, 0x1b, 0x1a, 0x79, 0x0d, 0x87, 0x8d,
	0xa7, 0xc2, 0x37, 0xb0, 0xe2, 0x64, 0x57, 0x45, 0x13, 0x20, 0xed, 0xa8, 0x67, 0x6f, 0xc1, 0x5d,
	0xbf, 0x4e, 0x02, 0x60, 0x7f, 0x1a, 0x45, 0x1f, 0x22, 0xea, 0x1d, 0x90, 0x43, 0x30, 0xc6, 0xd1,
	0xd4, 0xd3, 0x88, 0x0b, 0x56, 0x44, 0x69, 0x34, 0xf3, 0x74, 0x72, 0x0c, 0x2e, 0x8d, 0xaf, 0x63,
	0x1a, 0xdf, 0x8e, 0x62, 0xcf, 0x38, 0x1b, 0x80, 0xd3, 0x4d, 0x2d, 0x96, 0x26, 0xf4, 0x6e, 0x94,
	0x78, 0x07, 0x6a, 0x3d, 0xb9, 0x7c, 0x17, 0x8f, 0x12, 0x4f, 0x3b, 0x1b, 0x81, 0xd3, 0x3d, 0x57,
	0xe2, 0x80, 0x79, 0x39, 0xb9, 0x9a, 0x35, 0x8c, 0x9b, 0x38, 0xba, 0x8a, 0xa9, 0xa7, 0x91, 0xff,
	0xc0, 0xb9, 0x9e, 0xd0, 0xf1, 0x55, 0x94, 0x44, 0x9e, 0xae, 0xbe, 0xf6, 0xf1, 0x2e, 0xa6, 0x33,
	0xcf, 0x50, 0xf4, 0x69, 0x94, 0xdc, 0x78, 0xe6, 0x67, 0x1b, 0xff, 0x57, 0xaf, 0xfe, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x52, 0x7e, 0xdf, 0xc0, 0x04, 0x00, 0x00,
}
