// GENERATED: DO NOT EDIT
//
// This file contains base64 encodings of templates used for Swift OpenAPI code generation.
//
func loadTemplates() -> [String:String] {
  return [
    "client.swift": "Ly8gQ2xpZW50IGNvZGUgCgpjbGFzcyBDbGllbnQgewovLy17JSBmb3Igc2VydmljZU1ldGhvZCBpbiByZW5kZXJlci5tZXRob2RzICV9CgogIGZ1bmMge3sgc2VydmljZU1ldGhvZC5uYW1lIH19ICgpIHsKCiAgfQovLy17JSBlbmRmb3IgJX0KfQ==",
    "service.swift": "Ly8gU2VydmljZSBjb2RlCgpwcm90b2NvbCBTZXJ2aWNlIHsKLy8teyUgZm9yIHNlcnZpY2VNZXRob2QgaW4gcmVuZGVyZXIubWV0aG9kcyAlfQogIGZ1bmMge3sgc2VydmljZU1ldGhvZC5uYW1lIH19ICgpIAovLy17JSBlbmRmb3IgJX0KfQoKY2xhc3MgU2VydmVyIHsKCXByaXZhdGUgdmFyIHNlcnZpY2UgOiBTZXJ2aWNlCgkKCWluaXQoc2VydmljZSA6IFNlcnZpY2UpIHsKCQlzZWxmLnNlcnZpY2UgPSBzZXJ2aWNlCgl9Cn0=",
    "types.swift": "Ly8gQ29tbW9uIHR5cGUgZGVjbGFyYXRpb25zCgovLy17JSBmb3Igc2VydmljZVR5cGUgaW4gcmVuZGVyZXIudHlwZXMgJX0KY2xhc3Mge3sgc2VydmljZVR5cGUubmFtZSB9fSB7Ci8vLXslIGZvciBzZXJ2aWNlVHlwZUZpZWxkIGluIHNlcnZpY2VUeXBlLmZpZWxkcyAlfQogIHB1YmxpYyB2YXIge3tzZXJ2aWNlVHlwZUZpZWxkLm5hbWV9fSA6IHt7c2VydmljZVR5cGVGaWVsZC50eXBlTmFtZX19Ci8vLXslIGVuZGZvciAlfQp9CgovLy17JSBlbmRmb3IgJX0=",
  ]
}

