// Code generated by protoc-gen-go.
// source: extension.proto
// DO NOT EDIT!

/*
Package openapiextension_v1 is a generated protocol buffer package.

It is generated from these files:
	extension.proto

It has these top-level messages:
	Version
	ExtensionHandlerRequest
	ExtensionHandlerResponse
	Wrapper
*/
package openapiextension_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The version number of OpenAPI compiler.
type Version struct {
	Major int32 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor int32 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch int32 `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	// A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
	// be empty for mainline stable releases.
	Suffix string `protobuf:"bytes,4,opt,name=suffix" json:"suffix,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetMajor() int32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Version) GetMinor() int32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Version) GetPatch() int32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func (m *Version) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

// An encoded Request is written to the ExtensionHandler's stdin.
type ExtensionHandlerRequest struct {
	// The OpenAPI descriptions that were explicitly listed on the command line.
	// The specifications will appear in the order they are specified to openapic.
	Wrapper *Wrapper `protobuf:"bytes,1,opt,name=wrapper" json:"wrapper,omitempty"`
	// The version number of openapi compiler.
	CompilerVersion *Version `protobuf:"bytes,3,opt,name=compiler_version" json:"compiler_version,omitempty"`
}

func (m *ExtensionHandlerRequest) Reset()                    { *m = ExtensionHandlerRequest{} }
func (m *ExtensionHandlerRequest) String() string            { return proto.CompactTextString(m) }
func (*ExtensionHandlerRequest) ProtoMessage()               {}
func (*ExtensionHandlerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExtensionHandlerRequest) GetWrapper() *Wrapper {
	if m != nil {
		return m.Wrapper
	}
	return nil
}

func (m *ExtensionHandlerRequest) GetCompilerVersion() *Version {
	if m != nil {
		return m.CompilerVersion
	}
	return nil
}

// The extensions writes an encoded ExtensionHandlerResponse to stdout.
type ExtensionHandlerResponse struct {
	// true if the extension is handled by the extension handler; false otherwise
	Handled bool `protobuf:"varint,1,opt,name=handled" json:"handled,omitempty"`
	// Error message.  If non-empty, the extension handling failed.
	// The extension handler process should exit with status code zero
	// even if it reports an error in this way.
	//
	// This should be used to indicate errors which prevent the extension from
	// operating as intended.  Errors which indicate a problem in gnostic
	// itself -- such as the input Document being unparseable -- should be
	// reported by writing a message to stderr and exiting with a non-zero
	// status code.
	Error []string `protobuf:"bytes,2,rep,name=error" json:"error,omitempty"`
	// text output
	Value *google_protobuf.Any `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *ExtensionHandlerResponse) Reset()                    { *m = ExtensionHandlerResponse{} }
func (m *ExtensionHandlerResponse) String() string            { return proto.CompactTextString(m) }
func (*ExtensionHandlerResponse) ProtoMessage()               {}
func (*ExtensionHandlerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExtensionHandlerResponse) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

func (m *ExtensionHandlerResponse) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ExtensionHandlerResponse) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Wrapper struct {
	// version of the OpenAPI specification in which this extension was written.
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Name of the extension
	ExtensionName string `protobuf:"bytes,2,opt,name=extension_name" json:"extension_name,omitempty"`
	// Must be a valid yaml for the proto
	Yaml string `protobuf:"bytes,3,opt,name=yaml" json:"yaml,omitempty"`
}

func (m *Wrapper) Reset()                    { *m = Wrapper{} }
func (m *Wrapper) String() string            { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()               {}
func (*Wrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Wrapper) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Wrapper) GetExtensionName() string {
	if m != nil {
		return m.ExtensionName
	}
	return ""
}

func (m *Wrapper) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "openapiextension.v1.Version")
	proto.RegisterType((*ExtensionHandlerRequest)(nil), "openapiextension.v1.ExtensionHandlerRequest")
	proto.RegisterType((*ExtensionHandlerResponse)(nil), "openapiextension.v1.ExtensionHandlerResponse")
	proto.RegisterType((*Wrapper)(nil), "openapiextension.v1.Wrapper")
}

func init() { proto.RegisterFile("extension.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x14, 0xc4, 0x53, 0xfe, 0xd5, 0x3e, 0x95, 0x9a, 0xd5, 0x68, 0x35, 0x1e, 0x48, 0xbd, 0x70, 0x61,
	0x09, 0x9a, 0x78, 0x16, 0x12, 0x8c, 0x9e, 0x20, 0x1e, 0xf0, 0x48, 0x16, 0x78, 0x94, 0x9a, 0x76,
	0x77, 0xdd, 0xfe, 0x91, 0xde, 0xfc, 0x2c, 0x7e, 0x52, 0xd3, 0x2d, 0x8b, 0x07, 0xf5, 0xf8, 0x36,
	0xb3, 0x33, 0xbf, 0x19, 0x70, 0x71, 0x9b, 0x22, 0x4f, 0x42, 0xc1, 0xa9, 0x54, 0x22, 0x15, 0xe4,
	0x54, 0x48, 0xe4, 0x4c, 0x86, 0x3f, 0xef, 0xf9, 0xe0, 0xea, 0x32, 0x10, 0x22, 0x88, 0xb0, 0xaf,
	0x25, 0x8b, 0x6c, 0xdd, 0x67, 0xbc, 0xa8, 0xf4, 0xfe, 0x23, 0xd8, 0x33, 0x54, 0xa5, 0x90, 0x1c,
	0x43, 0x33, 0x66, 0x6f, 0x42, 0x79, 0x56, 0xc7, 0xea, 0x36, 0xf5, 0x19, 0x72, 0xa1, 0xbc, 0x9a,
	0x39, 0x25, 0x4b, 0x97, 0x1b, 0xaf, 0xae, 0xcf, 0x36, 0xb4, 0x92, 0x6c, 0xbd, 0x0e, 0xb7, 0x5e,
	0xa3, 0x63, 0x75, 0x1d, 0xff, 0xd3, 0x82, 0x8b, 0xb1, 0xc9, 0x7c, 0x62, 0x7c, 0x15, 0xa1, 0x7a,
	0xc1, 0xf7, 0x0c, 0x93, 0x94, 0xf4, 0xc0, 0xfe, 0x50, 0x4c, 0x4a, 0xac, 0xac, 0x0f, 0x6f, 0xaf,
	0xe9, 0x1f, 0x94, 0xf4, 0xb5, 0xd2, 0x90, 0x7b, 0x38, 0x59, 0x8a, 0x58, 0x86, 0x11, 0xaa, 0x79,
	0x5e, 0xb1, 0xe9, 0xd0, 0xff, 0xfe, 0xed, 0xf8, 0xfd, 0x39, 0x78, 0xbf, 0x09, 0x12, 0x29, 0x78,
	0x82, 0xc4, 0x05, 0x7b, 0xa3, 0x9f, 0x56, 0x1a, 0xe1, 0xa0, 0xac, 0x83, 0x4a, 0xe9, 0x76, 0xf5,
	0xae, 0x43, 0x6e, 0xa0, 0x99, 0xb3, 0x28, 0xc3, 0x5d, 0xd0, 0x19, 0xad, 0x16, 0xa3, 0x66, 0x31,
	0x3a, 0xe4, 0x85, 0xff, 0x00, 0xb6, 0x61, 0x74, 0xc1, 0x36, 0x68, 0xa5, 0x9f, 0x43, 0xce, 0xa1,
	0xbd, 0x87, 0x9a, 0x73, 0x16, 0xa3, 0x9e, 0xcd, 0x21, 0x47, 0xd0, 0x28, 0x58, 0x1c, 0x69, 0x5f,
	0x67, 0xd4, 0x03, 0x57, 0xa8, 0xc0, 0xb4, 0x58, 0xd2, 0x7c, 0x30, 0x22, 0x13, 0x89, 0x7c, 0x38,
	0x7d, 0xde, 0xa3, 0xcf, 0x06, 0x53, 0xeb, 0xab, 0x56, 0x9f, 0x0c, 0xc7, 0x8b, 0x96, 0x8e, 0xbf,
	0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x75, 0x9a, 0x1a, 0x2b, 0xe6, 0x01, 0x00, 0x00,
}
