// Copyright 2016 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED.

package OpenAPIv2

import (
	"fmt"
	"github.com/googleapis/openapi-compiler/helpers"
	"log"
)

func Version() string {
	return "OpenAPIv2"
}

func NewAdditionalPropertiesItem(in interface{}) *AdditionalPropertiesItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewAdditionalPropertiesItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"boolean", "schema"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &AdditionalPropertiesItem{}
	// Schema schema = 1;
	if helpers.MapHasKey(m, "schema") {
		x.Schema = NewSchema(helpers.MapValueForKey(m, "schema"))
	}
	// bool boolean = 2;
	if helpers.MapHasKey(m, "boolean") {
		x.Boolean = helpers.MapValueForKey(m, "boolean").(bool)
	}
	return x
}

func NewAny(in interface{}) *Any {
	x := &Any{}
	x.Value = fmt.Sprintf("%+v", in)
	return x
}

func NewApiKeySecurity(in interface{}) *ApiKeySecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewApiKeySecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"in", "name", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "in", "name", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &ApiKeySecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string name = 2;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string in = 3;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// string description = 4;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 5;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewBasicAuthenticationSecurity(in interface{}) *BasicAuthenticationSecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewBasicAuthenticationSecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &BasicAuthenticationSecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string description = 2;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 3;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewBodyParameter(in interface{}) *BodyParameter {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewBodyParameter: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"in", "name", "schema"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "in", "name", "required", "schema"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &BodyParameter{}
	// string description = 1;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string name = 2;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string in = 3;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// bool required = 4;
	if helpers.MapHasKey(m, "required") {
		x.Required = helpers.MapValueForKey(m, "required").(bool)
	}
	// Schema schema = 5;
	if helpers.MapHasKey(m, "schema") {
		x.Schema = NewSchema(helpers.MapValueForKey(m, "schema"))
	}
	// repeated NamedAny vendor_extension = 6;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewContact(in interface{}) *Contact {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewContact: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"email", "name", "url"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Contact{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string url = 2;
	if helpers.MapHasKey(m, "url") {
		x.Url = helpers.MapValueForKey(m, "url").(string)
	}
	// string email = 3;
	if helpers.MapHasKey(m, "email") {
		x.Email = helpers.MapValueForKey(m, "email").(string)
	}
	// repeated NamedAny vendor_extension = 4;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewDefault(in interface{}) *Default {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewDefault: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Default{}
	// repeated NamedAny additional_properties = 1;
	// MAP: Any
	x.AdditionalProperties = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedAny{}
		pair.Name = k
		pair.Value = NewAny(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewDefinitions(in interface{}) *Definitions {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewDefinitions: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Definitions{}
	// repeated NamedSchema additional_properties = 1;
	// MAP: Schema
	x.AdditionalProperties = make([]*NamedSchema, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedSchema{}
		pair.Name = k
		pair.Value = NewSchema(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewDocument(in interface{}) *Document {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewDocument: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"info", "paths", "swagger"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"basePath", "consumes", "definitions", "externalDocs", "host", "info", "parameters", "paths", "produces", "responses", "schemes", "security", "securityDefinitions", "swagger", "tags"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Document{}
	// string swagger = 1;
	if helpers.MapHasKey(m, "swagger") {
		x.Swagger = helpers.MapValueForKey(m, "swagger").(string)
	}
	// Info info = 2;
	if helpers.MapHasKey(m, "info") {
		x.Info = NewInfo(helpers.MapValueForKey(m, "info"))
	}
	// string host = 3;
	if helpers.MapHasKey(m, "host") {
		x.Host = helpers.MapValueForKey(m, "host").(string)
	}
	// string base_path = 4;
	if helpers.MapHasKey(m, "basePath") {
		x.BasePath = helpers.MapValueForKey(m, "basePath").(string)
	}
	// repeated string schemes = 5;
	if helpers.MapHasKey(m, "schemes") {
		v, ok := helpers.MapValueForKey(m, "schemes").([]interface{})
		if ok {
			x.Schemes = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "schemes"))
		}
	}
	// repeated string consumes = 6;
	if helpers.MapHasKey(m, "consumes") {
		v, ok := helpers.MapValueForKey(m, "consumes").([]interface{})
		if ok {
			x.Consumes = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "consumes"))
		}
	}
	// repeated string produces = 7;
	if helpers.MapHasKey(m, "produces") {
		v, ok := helpers.MapValueForKey(m, "produces").([]interface{})
		if ok {
			x.Produces = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "produces"))
		}
	}
	// Paths paths = 8;
	if helpers.MapHasKey(m, "paths") {
		x.Paths = NewPaths(helpers.MapValueForKey(m, "paths"))
	}
	// Definitions definitions = 9;
	if helpers.MapHasKey(m, "definitions") {
		x.Definitions = NewDefinitions(helpers.MapValueForKey(m, "definitions"))
	}
	// ParameterDefinitions parameters = 10;
	if helpers.MapHasKey(m, "parameters") {
		x.Parameters = NewParameterDefinitions(helpers.MapValueForKey(m, "parameters"))
	}
	// ResponseDefinitions responses = 11;
	if helpers.MapHasKey(m, "responses") {
		x.Responses = NewResponseDefinitions(helpers.MapValueForKey(m, "responses"))
	}
	// repeated SecurityRequirement security = 12;
	if helpers.MapHasKey(m, "security") {
		// repeated class SecurityRequirement
		x.Security = make([]*SecurityRequirement, 0)
		a, ok := helpers.MapValueForKey(m, "security").([]interface{})
		if ok {
			for _, item := range a {
				x.Security = append(x.Security, NewSecurityRequirement(item))
			}
		}
	}
	// SecurityDefinitions security_definitions = 13;
	if helpers.MapHasKey(m, "securityDefinitions") {
		x.SecurityDefinitions = NewSecurityDefinitions(helpers.MapValueForKey(m, "securityDefinitions"))
	}
	// repeated Tag tags = 14;
	if helpers.MapHasKey(m, "tags") {
		// repeated class Tag
		x.Tags = make([]*Tag, 0)
		a, ok := helpers.MapValueForKey(m, "tags").([]interface{})
		if ok {
			for _, item := range a {
				x.Tags = append(x.Tags, NewTag(item))
			}
		}
	}
	// ExternalDocs external_docs = 15;
	if helpers.MapHasKey(m, "externalDocs") {
		x.ExternalDocs = NewExternalDocs(helpers.MapValueForKey(m, "externalDocs"))
	}
	return x
}

func NewExamples(in interface{}) *Examples {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewExamples: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Examples{}
	// repeated NamedAny additional_properties = 1;
	// MAP: Any
	x.AdditionalProperties = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedAny{}
		pair.Name = k
		pair.Value = NewAny(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewExternalDocs(in interface{}) *ExternalDocs {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewExternalDocs: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"url"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "url"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &ExternalDocs{}
	// string description = 1;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string url = 2;
	if helpers.MapHasKey(m, "url") {
		x.Url = helpers.MapValueForKey(m, "url").(string)
	}
	// repeated NamedAny vendor_extension = 3;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewFileSchema(in interface{}) *FileSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewFileSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"default", "description", "example", "externalDocs", "format", "readOnly", "required", "title", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &FileSchema{}
	// string format = 1;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// string title = 2;
	if helpers.MapHasKey(m, "title") {
		x.Title = helpers.MapValueForKey(m, "title").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// Any default = 4;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// repeated string required = 5;
	if helpers.MapHasKey(m, "required") {
		v, ok := helpers.MapValueForKey(m, "required").([]interface{})
		if ok {
			x.Required = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "required"))
		}
	}
	// string type = 6;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// bool read_only = 7;
	if helpers.MapHasKey(m, "readOnly") {
		x.ReadOnly = helpers.MapValueForKey(m, "readOnly").(bool)
	}
	// ExternalDocs external_docs = 8;
	if helpers.MapHasKey(m, "externalDocs") {
		x.ExternalDocs = NewExternalDocs(helpers.MapValueForKey(m, "externalDocs"))
	}
	// Any example = 9;
	if helpers.MapHasKey(m, "example") {
		x.Example = NewAny(helpers.MapValueForKey(m, "example"))
	}
	// repeated NamedAny vendor_extension = 10;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewFormDataParameterSubSchema(in interface{}) *FormDataParameterSubSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewFormDataParameterSubSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"allowEmptyValue", "collectionFormat", "default", "description", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "in", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "name", "pattern", "required", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &FormDataParameterSubSchema{}
	// bool required = 1;
	if helpers.MapHasKey(m, "required") {
		x.Required = helpers.MapValueForKey(m, "required").(bool)
	}
	// string in = 2;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string name = 4;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// bool allow_empty_value = 5;
	if helpers.MapHasKey(m, "allowEmptyValue") {
		x.AllowEmptyValue = helpers.MapValueForKey(m, "allowEmptyValue").(bool)
	}
	// string type = 6;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 7;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 8;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 9;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 10;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 11;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 12;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 13;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 14;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 15;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 16;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 17;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 18;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 19;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 20;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 21;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 22;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// repeated NamedAny vendor_extension = 23;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewHeader(in interface{}) *Header {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewHeader: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"collectionFormat", "default", "description", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "pattern", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Header{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 2;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 3;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 4;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 5;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 6;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 7;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 8;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 9;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 10;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 11;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 12;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 13;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 14;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 15;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 16;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 17;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// string description = 18;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 19;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewHeaderParameterSubSchema(in interface{}) *HeaderParameterSubSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewHeaderParameterSubSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"collectionFormat", "default", "description", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "in", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "name", "pattern", "required", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &HeaderParameterSubSchema{}
	// bool required = 1;
	if helpers.MapHasKey(m, "required") {
		x.Required = helpers.MapValueForKey(m, "required").(bool)
	}
	// string in = 2;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string name = 4;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string type = 5;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 6;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 7;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 8;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 9;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 10;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 11;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 12;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 13;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 14;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 15;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 16;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 17;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 18;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 19;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 20;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 21;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// repeated NamedAny vendor_extension = 22;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewHeaders(in interface{}) *Headers {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewHeaders: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Headers{}
	// repeated NamedHeader additional_properties = 1;
	// MAP: Header
	x.AdditionalProperties = make([]*NamedHeader, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedHeader{}
		pair.Name = k
		pair.Value = NewHeader(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewInfo(in interface{}) *Info {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewInfo: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"title", "version"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"contact", "description", "license", "termsOfService", "title", "version"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Info{}
	// string title = 1;
	if helpers.MapHasKey(m, "title") {
		x.Title = helpers.MapValueForKey(m, "title").(string)
	}
	// string version = 2;
	if helpers.MapHasKey(m, "version") {
		x.Version = helpers.MapValueForKey(m, "version").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string terms_of_service = 4;
	if helpers.MapHasKey(m, "termsOfService") {
		x.TermsOfService = helpers.MapValueForKey(m, "termsOfService").(string)
	}
	// Contact contact = 5;
	if helpers.MapHasKey(m, "contact") {
		x.Contact = NewContact(helpers.MapValueForKey(m, "contact"))
	}
	// License license = 6;
	if helpers.MapHasKey(m, "license") {
		x.License = NewLicense(helpers.MapValueForKey(m, "license"))
	}
	// repeated NamedAny vendor_extension = 7;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewItemsItem(in interface{}) *ItemsItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewItemsItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &ItemsItem{}
	if ok {
		x.Schema = make([]*Schema, 0)
		x.Schema = append(x.Schema, NewSchema(m))
	} else {
		log.Printf("unexpected: %+v", in)
	}
	return x
}

func NewJsonReference(in interface{}) *JsonReference {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewJsonReference: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"$ref"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"$ref"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &JsonReference{}
	// string _ref = 1;
	if helpers.MapHasKey(m, "$ref") {
		x.XRef = helpers.MapValueForKey(m, "$ref").(string)
	}
	return x
}

func NewLicense(in interface{}) *License {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewLicense: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"name"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"name", "url"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &License{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string url = 2;
	if helpers.MapHasKey(m, "url") {
		x.Url = helpers.MapValueForKey(m, "url").(string)
	}
	// repeated NamedAny vendor_extension = 3;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewNamedAny(in interface{}) *NamedAny {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedAny: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedAny{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// Any value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewAny(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedHeader(in interface{}) *NamedHeader {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedHeader: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedHeader{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// Header value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewHeader(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedParameter(in interface{}) *NamedParameter {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedParameter: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedParameter{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// Parameter value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewParameter(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedPathItem(in interface{}) *NamedPathItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedPathItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedPathItem{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// PathItem value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewPathItem(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedResponse(in interface{}) *NamedResponse {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedResponse: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedResponse{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// Response value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewResponse(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedResponseValue(in interface{}) *NamedResponseValue {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedResponseValue: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedResponseValue{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// ResponseValue value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewResponseValue(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedSchema(in interface{}) *NamedSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedSchema{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// Schema value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewSchema(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedSecurityDefinitionsItem(in interface{}) *NamedSecurityDefinitionsItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedSecurityDefinitionsItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedSecurityDefinitionsItem{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// SecurityDefinitionsItem value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewSecurityDefinitionsItem(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNamedString(in interface{}) *NamedString {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedString: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedString{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = helpers.MapValueForKey(m, "value").(string)
	}
	return x
}

func NewNamedStringArray(in interface{}) *NamedStringArray {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNamedStringArray: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"name", "value"}
	allowedPatterns := []string{}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &NamedStringArray{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// StringArray value = 2;
	if helpers.MapHasKey(m, "value") {
		x.Value = NewStringArray(helpers.MapValueForKey(m, "value"))
	}
	return x
}

func NewNonBodyParameter(in interface{}) *NonBodyParameter {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewNonBodyParameter: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"in", "name", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	x := &NonBodyParameter{}
	// HeaderParameterSubSchema header_parameter_sub_schema = 1;
	{
		t := NewHeaderParameterSubSchema(m)
		if t != nil {
			x.Oneof = &NonBodyParameter_HeaderParameterSubSchema{HeaderParameterSubSchema: t}
		}
	}
	// FormDataParameterSubSchema form_data_parameter_sub_schema = 2;
	{
		t := NewFormDataParameterSubSchema(m)
		if t != nil {
			x.Oneof = &NonBodyParameter_FormDataParameterSubSchema{FormDataParameterSubSchema: t}
		}
	}
	// QueryParameterSubSchema query_parameter_sub_schema = 3;
	{
		t := NewQueryParameterSubSchema(m)
		if t != nil {
			x.Oneof = &NonBodyParameter_QueryParameterSubSchema{QueryParameterSubSchema: t}
		}
	}
	// PathParameterSubSchema path_parameter_sub_schema = 4;
	{
		t := NewPathParameterSubSchema(m)
		if t != nil {
			x.Oneof = &NonBodyParameter_PathParameterSubSchema{PathParameterSubSchema: t}
		}
	}
	return x
}

func NewOauth2AccessCodeSecurity(in interface{}) *Oauth2AccessCodeSecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOauth2AccessCodeSecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"authorizationUrl", "flow", "tokenUrl", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"authorizationUrl", "description", "flow", "scopes", "tokenUrl", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Oauth2AccessCodeSecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string flow = 2;
	if helpers.MapHasKey(m, "flow") {
		x.Flow = helpers.MapValueForKey(m, "flow").(string)
	}
	// Oauth2Scopes scopes = 3;
	if helpers.MapHasKey(m, "scopes") {
		x.Scopes = NewOauth2Scopes(helpers.MapValueForKey(m, "scopes"))
	}
	// string authorization_url = 4;
	if helpers.MapHasKey(m, "authorizationUrl") {
		x.AuthorizationUrl = helpers.MapValueForKey(m, "authorizationUrl").(string)
	}
	// string token_url = 5;
	if helpers.MapHasKey(m, "tokenUrl") {
		x.TokenUrl = helpers.MapValueForKey(m, "tokenUrl").(string)
	}
	// string description = 6;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 7;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewOauth2ApplicationSecurity(in interface{}) *Oauth2ApplicationSecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOauth2ApplicationSecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"flow", "tokenUrl", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "flow", "scopes", "tokenUrl", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Oauth2ApplicationSecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string flow = 2;
	if helpers.MapHasKey(m, "flow") {
		x.Flow = helpers.MapValueForKey(m, "flow").(string)
	}
	// Oauth2Scopes scopes = 3;
	if helpers.MapHasKey(m, "scopes") {
		x.Scopes = NewOauth2Scopes(helpers.MapValueForKey(m, "scopes"))
	}
	// string token_url = 4;
	if helpers.MapHasKey(m, "tokenUrl") {
		x.TokenUrl = helpers.MapValueForKey(m, "tokenUrl").(string)
	}
	// string description = 5;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 6;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewOauth2ImplicitSecurity(in interface{}) *Oauth2ImplicitSecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOauth2ImplicitSecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"authorizationUrl", "flow", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"authorizationUrl", "description", "flow", "scopes", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Oauth2ImplicitSecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string flow = 2;
	if helpers.MapHasKey(m, "flow") {
		x.Flow = helpers.MapValueForKey(m, "flow").(string)
	}
	// Oauth2Scopes scopes = 3;
	if helpers.MapHasKey(m, "scopes") {
		x.Scopes = NewOauth2Scopes(helpers.MapValueForKey(m, "scopes"))
	}
	// string authorization_url = 4;
	if helpers.MapHasKey(m, "authorizationUrl") {
		x.AuthorizationUrl = helpers.MapValueForKey(m, "authorizationUrl").(string)
	}
	// string description = 5;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 6;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewOauth2PasswordSecurity(in interface{}) *Oauth2PasswordSecurity {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOauth2PasswordSecurity: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"flow", "tokenUrl", "type"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "flow", "scopes", "tokenUrl", "type"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Oauth2PasswordSecurity{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string flow = 2;
	if helpers.MapHasKey(m, "flow") {
		x.Flow = helpers.MapValueForKey(m, "flow").(string)
	}
	// Oauth2Scopes scopes = 3;
	if helpers.MapHasKey(m, "scopes") {
		x.Scopes = NewOauth2Scopes(helpers.MapValueForKey(m, "scopes"))
	}
	// string token_url = 4;
	if helpers.MapHasKey(m, "tokenUrl") {
		x.TokenUrl = helpers.MapValueForKey(m, "tokenUrl").(string)
	}
	// string description = 5;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// repeated NamedAny vendor_extension = 6;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewOauth2Scopes(in interface{}) *Oauth2Scopes {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOauth2Scopes: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Oauth2Scopes{}
	// repeated NamedString additional_properties = 1;
	// MAP: string
	x.AdditionalProperties = make([]*NamedString, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedString{}
		pair.Name = k
		pair.Value = v.(string)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewOperation(in interface{}) *Operation {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewOperation: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"responses"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"consumes", "deprecated", "description", "externalDocs", "operationId", "parameters", "produces", "responses", "schemes", "security", "summary", "tags"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Operation{}
	// repeated string tags = 1;
	if helpers.MapHasKey(m, "tags") {
		v, ok := helpers.MapValueForKey(m, "tags").([]interface{})
		if ok {
			x.Tags = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "tags"))
		}
	}
	// string summary = 2;
	if helpers.MapHasKey(m, "summary") {
		x.Summary = helpers.MapValueForKey(m, "summary").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// ExternalDocs external_docs = 4;
	if helpers.MapHasKey(m, "externalDocs") {
		x.ExternalDocs = NewExternalDocs(helpers.MapValueForKey(m, "externalDocs"))
	}
	// string operation_id = 5;
	if helpers.MapHasKey(m, "operationId") {
		x.OperationId = helpers.MapValueForKey(m, "operationId").(string)
	}
	// repeated string produces = 6;
	if helpers.MapHasKey(m, "produces") {
		v, ok := helpers.MapValueForKey(m, "produces").([]interface{})
		if ok {
			x.Produces = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "produces"))
		}
	}
	// repeated string consumes = 7;
	if helpers.MapHasKey(m, "consumes") {
		v, ok := helpers.MapValueForKey(m, "consumes").([]interface{})
		if ok {
			x.Consumes = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "consumes"))
		}
	}
	// repeated ParametersItem parameters = 8;
	if helpers.MapHasKey(m, "parameters") {
		// repeated class ParametersItem
		x.Parameters = make([]*ParametersItem, 0)
		a, ok := helpers.MapValueForKey(m, "parameters").([]interface{})
		if ok {
			for _, item := range a {
				x.Parameters = append(x.Parameters, NewParametersItem(item))
			}
		}
	}
	// Responses responses = 9;
	if helpers.MapHasKey(m, "responses") {
		x.Responses = NewResponses(helpers.MapValueForKey(m, "responses"))
	}
	// repeated string schemes = 10;
	if helpers.MapHasKey(m, "schemes") {
		v, ok := helpers.MapValueForKey(m, "schemes").([]interface{})
		if ok {
			x.Schemes = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "schemes"))
		}
	}
	// bool deprecated = 11;
	if helpers.MapHasKey(m, "deprecated") {
		x.Deprecated = helpers.MapValueForKey(m, "deprecated").(bool)
	}
	// repeated SecurityRequirement security = 12;
	if helpers.MapHasKey(m, "security") {
		// repeated class SecurityRequirement
		x.Security = make([]*SecurityRequirement, 0)
		a, ok := helpers.MapValueForKey(m, "security").([]interface{})
		if ok {
			for _, item := range a {
				x.Security = append(x.Security, NewSecurityRequirement(item))
			}
		}
	}
	// repeated NamedAny vendor_extension = 13;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewParameter(in interface{}) *Parameter {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewParameter: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Parameter{}
	// BodyParameter body_parameter = 1;
	{
		t := NewBodyParameter(m)
		if t != nil {
			x.Oneof = &Parameter_BodyParameter{BodyParameter: t}
		}
	}
	// NonBodyParameter non_body_parameter = 2;
	{
		t := NewNonBodyParameter(m)
		if t != nil {
			x.Oneof = &Parameter_NonBodyParameter{NonBodyParameter: t}
		}
	}
	return x
}

func NewParameterDefinitions(in interface{}) *ParameterDefinitions {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewParameterDefinitions: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &ParameterDefinitions{}
	// repeated NamedParameter additional_properties = 1;
	// MAP: Parameter
	x.AdditionalProperties = make([]*NamedParameter, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedParameter{}
		pair.Name = k
		pair.Value = NewParameter(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewParametersItem(in interface{}) *ParametersItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewParametersItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &ParametersItem{}
	// Parameter parameter = 1;
	{
		t := NewParameter(m)
		if t != nil {
			x.Oneof = &ParametersItem_Parameter{Parameter: t}
		}
	}
	// JsonReference json_reference = 2;
	{
		t := NewJsonReference(m)
		if t != nil {
			x.Oneof = &ParametersItem_JsonReference{JsonReference: t}
		}
	}
	return x
}

func NewPathItem(in interface{}) *PathItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewPathItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"$ref", "delete", "get", "head", "options", "parameters", "patch", "post", "put"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &PathItem{}
	// string _ref = 1;
	if helpers.MapHasKey(m, "$ref") {
		x.XRef = helpers.MapValueForKey(m, "$ref").(string)
	}
	// Operation get = 2;
	if helpers.MapHasKey(m, "get") {
		x.Get = NewOperation(helpers.MapValueForKey(m, "get"))
	}
	// Operation put = 3;
	if helpers.MapHasKey(m, "put") {
		x.Put = NewOperation(helpers.MapValueForKey(m, "put"))
	}
	// Operation post = 4;
	if helpers.MapHasKey(m, "post") {
		x.Post = NewOperation(helpers.MapValueForKey(m, "post"))
	}
	// Operation delete = 5;
	if helpers.MapHasKey(m, "delete") {
		x.Delete = NewOperation(helpers.MapValueForKey(m, "delete"))
	}
	// Operation options = 6;
	if helpers.MapHasKey(m, "options") {
		x.Options = NewOperation(helpers.MapValueForKey(m, "options"))
	}
	// Operation head = 7;
	if helpers.MapHasKey(m, "head") {
		x.Head = NewOperation(helpers.MapValueForKey(m, "head"))
	}
	// Operation patch = 8;
	if helpers.MapHasKey(m, "patch") {
		x.Patch = NewOperation(helpers.MapValueForKey(m, "patch"))
	}
	// repeated ParametersItem parameters = 9;
	if helpers.MapHasKey(m, "parameters") {
		// repeated class ParametersItem
		x.Parameters = make([]*ParametersItem, 0)
		a, ok := helpers.MapValueForKey(m, "parameters").([]interface{})
		if ok {
			for _, item := range a {
				x.Parameters = append(x.Parameters, NewParametersItem(item))
			}
		}
	}
	// repeated NamedAny vendor_extension = 10;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewPathParameterSubSchema(in interface{}) *PathParameterSubSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewPathParameterSubSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"required"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"collectionFormat", "default", "description", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "in", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "name", "pattern", "required", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &PathParameterSubSchema{}
	// bool required = 1;
	if helpers.MapHasKey(m, "required") {
		x.Required = helpers.MapValueForKey(m, "required").(bool)
	}
	// string in = 2;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string name = 4;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string type = 5;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 6;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 7;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 8;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 9;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 10;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 11;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 12;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 13;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 14;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 15;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 16;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 17;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 18;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 19;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 20;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 21;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// repeated NamedAny vendor_extension = 22;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewPaths(in interface{}) *Paths {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewPaths: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{}
	allowedPatterns := []string{"^x-", "^/"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Paths{}
	// repeated NamedAny vendor_extension = 1;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	// repeated NamedPathItem path = 2;
	// MAP: PathItem ^/
	x.Path = make([]*NamedPathItem, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^/", k) {
			pair := &NamedPathItem{}
			pair.Name = k
			pair.Value = NewPathItem(v)
			x.Path = append(x.Path, pair)
		}
	}
	return x
}

func NewPrimitivesItems(in interface{}) *PrimitivesItems {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewPrimitivesItems: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"collectionFormat", "default", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "pattern", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &PrimitivesItems{}
	// string type = 1;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 2;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 3;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 4;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 5;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 6;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 7;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 8;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 9;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 10;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 11;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 12;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 13;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 14;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 15;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 16;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 17;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// repeated NamedAny vendor_extension = 18;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewProperties(in interface{}) *Properties {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewProperties: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &Properties{}
	// repeated NamedSchema additional_properties = 1;
	// MAP: Schema
	x.AdditionalProperties = make([]*NamedSchema, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedSchema{}
		pair.Name = k
		pair.Value = NewSchema(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewQueryParameterSubSchema(in interface{}) *QueryParameterSubSchema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewQueryParameterSubSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"allowEmptyValue", "collectionFormat", "default", "description", "enum", "exclusiveMaximum", "exclusiveMinimum", "format", "in", "items", "maxItems", "maxLength", "maximum", "minItems", "minLength", "minimum", "multipleOf", "name", "pattern", "required", "type", "uniqueItems"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &QueryParameterSubSchema{}
	// bool required = 1;
	if helpers.MapHasKey(m, "required") {
		x.Required = helpers.MapValueForKey(m, "required").(bool)
	}
	// string in = 2;
	if helpers.MapHasKey(m, "in") {
		x.In = helpers.MapValueForKey(m, "in").(string)
	}
	// string description = 3;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// string name = 4;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// bool allow_empty_value = 5;
	if helpers.MapHasKey(m, "allowEmptyValue") {
		x.AllowEmptyValue = helpers.MapValueForKey(m, "allowEmptyValue").(bool)
	}
	// string type = 6;
	if helpers.MapHasKey(m, "type") {
		x.Type = helpers.MapValueForKey(m, "type").(string)
	}
	// string format = 7;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// PrimitivesItems items = 8;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewPrimitivesItems(helpers.MapValueForKey(m, "items"))
	}
	// string collection_format = 9;
	if helpers.MapHasKey(m, "collectionFormat") {
		x.CollectionFormat = helpers.MapValueForKey(m, "collectionFormat").(string)
	}
	// Any default = 10;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float maximum = 11;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 12;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 13;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 14;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 15;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 16;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 17;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 18;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 19;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 20;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// repeated Any enum = 21;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// float multiple_of = 22;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// repeated NamedAny vendor_extension = 23;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewResponse(in interface{}) *Response {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewResponse: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"description"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "examples", "headers", "schema"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Response{}
	// string description = 1;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// SchemaItem schema = 2;
	if helpers.MapHasKey(m, "schema") {
		x.Schema = NewSchemaItem(helpers.MapValueForKey(m, "schema"))
	}
	// Headers headers = 3;
	if helpers.MapHasKey(m, "headers") {
		x.Headers = NewHeaders(helpers.MapValueForKey(m, "headers"))
	}
	// Examples examples = 4;
	if helpers.MapHasKey(m, "examples") {
		x.Examples = NewExamples(helpers.MapValueForKey(m, "examples"))
	}
	// repeated NamedAny vendor_extension = 5;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewResponseDefinitions(in interface{}) *ResponseDefinitions {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewResponseDefinitions: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &ResponseDefinitions{}
	// repeated NamedResponse additional_properties = 1;
	// MAP: Response
	x.AdditionalProperties = make([]*NamedResponse, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedResponse{}
		pair.Name = k
		pair.Value = NewResponse(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewResponseValue(in interface{}) *ResponseValue {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewResponseValue: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &ResponseValue{}
	// Response response = 1;
	{
		t := NewResponse(m)
		if t != nil {
			x.Oneof = &ResponseValue_Response{Response: t}
		}
	}
	// JsonReference json_reference = 2;
	{
		t := NewJsonReference(m)
		if t != nil {
			x.Oneof = &ResponseValue_JsonReference{JsonReference: t}
		}
	}
	return x
}

func NewResponses(in interface{}) *Responses {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewResponses: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{}
	allowedPatterns := []string{"^([0-9]{3})$|^(default)$", "^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Responses{}
	// repeated NamedResponseValue response_code = 1;
	// MAP: ResponseValue ^([0-9]{3})$|^(default)$
	x.ResponseCode = make([]*NamedResponseValue, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^([0-9]{3})$|^(default)$", k) {
			pair := &NamedResponseValue{}
			pair.Name = k
			pair.Value = NewResponseValue(v)
			x.ResponseCode = append(x.ResponseCode, pair)
		}
	}
	// repeated NamedAny vendor_extension = 2;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewSchema(in interface{}) *Schema {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewSchema: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"$ref", "additionalProperties", "allOf", "default", "description", "discriminator", "enum", "example", "exclusiveMaximum", "exclusiveMinimum", "externalDocs", "format", "items", "maxItems", "maxLength", "maxProperties", "maximum", "minItems", "minLength", "minProperties", "minimum", "multipleOf", "pattern", "properties", "readOnly", "required", "title", "type", "uniqueItems", "xml"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Schema{}
	// string _ref = 1;
	if helpers.MapHasKey(m, "$ref") {
		x.XRef = helpers.MapValueForKey(m, "$ref").(string)
	}
	// string format = 2;
	if helpers.MapHasKey(m, "format") {
		x.Format = helpers.MapValueForKey(m, "format").(string)
	}
	// string title = 3;
	if helpers.MapHasKey(m, "title") {
		x.Title = helpers.MapValueForKey(m, "title").(string)
	}
	// string description = 4;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// Any default = 5;
	if helpers.MapHasKey(m, "default") {
		x.Default = NewAny(helpers.MapValueForKey(m, "default"))
	}
	// float multiple_of = 6;
	if helpers.MapHasKey(m, "multipleOf") {
		x.MultipleOf = helpers.MapValueForKey(m, "multipleOf").(float64)
	}
	// float maximum = 7;
	if helpers.MapHasKey(m, "maximum") {
		x.Maximum = helpers.MapValueForKey(m, "maximum").(float64)
	}
	// bool exclusive_maximum = 8;
	if helpers.MapHasKey(m, "exclusiveMaximum") {
		x.ExclusiveMaximum = helpers.MapValueForKey(m, "exclusiveMaximum").(bool)
	}
	// float minimum = 9;
	if helpers.MapHasKey(m, "minimum") {
		x.Minimum = helpers.MapValueForKey(m, "minimum").(float64)
	}
	// bool exclusive_minimum = 10;
	if helpers.MapHasKey(m, "exclusiveMinimum") {
		x.ExclusiveMinimum = helpers.MapValueForKey(m, "exclusiveMinimum").(bool)
	}
	// int64 max_length = 11;
	if helpers.MapHasKey(m, "maxLength") {
		x.MaxLength = helpers.MapValueForKey(m, "maxLength").(int64)
	}
	// int64 min_length = 12;
	if helpers.MapHasKey(m, "minLength") {
		x.MinLength = helpers.MapValueForKey(m, "minLength").(int64)
	}
	// string pattern = 13;
	if helpers.MapHasKey(m, "pattern") {
		x.Pattern = helpers.MapValueForKey(m, "pattern").(string)
	}
	// int64 max_items = 14;
	if helpers.MapHasKey(m, "maxItems") {
		x.MaxItems = helpers.MapValueForKey(m, "maxItems").(int64)
	}
	// int64 min_items = 15;
	if helpers.MapHasKey(m, "minItems") {
		x.MinItems = helpers.MapValueForKey(m, "minItems").(int64)
	}
	// bool unique_items = 16;
	if helpers.MapHasKey(m, "uniqueItems") {
		x.UniqueItems = helpers.MapValueForKey(m, "uniqueItems").(bool)
	}
	// int64 max_properties = 17;
	if helpers.MapHasKey(m, "maxProperties") {
		x.MaxProperties = helpers.MapValueForKey(m, "maxProperties").(int64)
	}
	// int64 min_properties = 18;
	if helpers.MapHasKey(m, "minProperties") {
		x.MinProperties = helpers.MapValueForKey(m, "minProperties").(int64)
	}
	// repeated string required = 19;
	if helpers.MapHasKey(m, "required") {
		v, ok := helpers.MapValueForKey(m, "required").([]interface{})
		if ok {
			x.Required = helpers.ConvertInterfaceArrayToStringArray(v)
		} else {
			log.Printf("unexpected: %+v", helpers.MapValueForKey(m, "required"))
		}
	}
	// repeated Any enum = 20;
	if helpers.MapHasKey(m, "enum") {
		// repeated class Any
		x.Enum = make([]*Any, 0)
		a, ok := helpers.MapValueForKey(m, "enum").([]interface{})
		if ok {
			for _, item := range a {
				x.Enum = append(x.Enum, NewAny(item))
			}
		}
	}
	// AdditionalPropertiesItem additional_properties = 21;
	if helpers.MapHasKey(m, "additionalProperties") {
		x.AdditionalProperties = NewAdditionalPropertiesItem(helpers.MapValueForKey(m, "additionalProperties"))
	}
	// TypeItem type = 22;
	if helpers.MapHasKey(m, "type") {
		x.Type = NewTypeItem(helpers.MapValueForKey(m, "type"))
	}
	// ItemsItem items = 23;
	if helpers.MapHasKey(m, "items") {
		x.Items = NewItemsItem(helpers.MapValueForKey(m, "items"))
	}
	// repeated Schema all_of = 24;
	if helpers.MapHasKey(m, "allOf") {
		// repeated class Schema
		x.AllOf = make([]*Schema, 0)
		a, ok := helpers.MapValueForKey(m, "allOf").([]interface{})
		if ok {
			for _, item := range a {
				x.AllOf = append(x.AllOf, NewSchema(item))
			}
		}
	}
	// Properties properties = 25;
	if helpers.MapHasKey(m, "properties") {
		x.Properties = NewProperties(helpers.MapValueForKey(m, "properties"))
	}
	// string discriminator = 26;
	if helpers.MapHasKey(m, "discriminator") {
		x.Discriminator = helpers.MapValueForKey(m, "discriminator").(string)
	}
	// bool read_only = 27;
	if helpers.MapHasKey(m, "readOnly") {
		x.ReadOnly = helpers.MapValueForKey(m, "readOnly").(bool)
	}
	// Xml xml = 28;
	if helpers.MapHasKey(m, "xml") {
		x.Xml = NewXml(helpers.MapValueForKey(m, "xml"))
	}
	// ExternalDocs external_docs = 29;
	if helpers.MapHasKey(m, "externalDocs") {
		x.ExternalDocs = NewExternalDocs(helpers.MapValueForKey(m, "externalDocs"))
	}
	// Any example = 30;
	if helpers.MapHasKey(m, "example") {
		x.Example = NewAny(helpers.MapValueForKey(m, "example"))
	}
	// repeated NamedAny vendor_extension = 31;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewSchemaItem(in interface{}) *SchemaItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewSchemaItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &SchemaItem{}
	// Schema schema = 1;
	{
		t := NewSchema(m)
		if t != nil {
			x.Oneof = &SchemaItem_Schema{Schema: t}
		}
	}
	// FileSchema file_schema = 2;
	{
		t := NewFileSchema(m)
		if t != nil {
			x.Oneof = &SchemaItem_FileSchema{FileSchema: t}
		}
	}
	return x
}

func NewSecurityDefinitions(in interface{}) *SecurityDefinitions {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewSecurityDefinitions: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &SecurityDefinitions{}
	// repeated NamedSecurityDefinitionsItem additional_properties = 1;
	// MAP: SecurityDefinitionsItem
	x.AdditionalProperties = make([]*NamedSecurityDefinitionsItem, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedSecurityDefinitionsItem{}
		pair.Name = k
		pair.Value = NewSecurityDefinitionsItem(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewSecurityDefinitionsItem(in interface{}) *SecurityDefinitionsItem {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewSecurityDefinitionsItem: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &SecurityDefinitionsItem{}
	// BasicAuthenticationSecurity basic_authentication_security = 1;
	{
		t := NewBasicAuthenticationSecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_BasicAuthenticationSecurity{BasicAuthenticationSecurity: t}
		}
	}
	// ApiKeySecurity api_key_security = 2;
	{
		t := NewApiKeySecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_ApiKeySecurity{ApiKeySecurity: t}
		}
	}
	// Oauth2ImplicitSecurity oauth2_implicit_security = 3;
	{
		t := NewOauth2ImplicitSecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_Oauth2ImplicitSecurity{Oauth2ImplicitSecurity: t}
		}
	}
	// Oauth2PasswordSecurity oauth2_password_security = 4;
	{
		t := NewOauth2PasswordSecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_Oauth2PasswordSecurity{Oauth2PasswordSecurity: t}
		}
	}
	// Oauth2ApplicationSecurity oauth2_application_security = 5;
	{
		t := NewOauth2ApplicationSecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_Oauth2ApplicationSecurity{Oauth2ApplicationSecurity: t}
		}
	}
	// Oauth2AccessCodeSecurity oauth2_access_code_security = 6;
	{
		t := NewOauth2AccessCodeSecurity(m)
		if t != nil {
			x.Oneof = &SecurityDefinitionsItem_Oauth2AccessCodeSecurity{Oauth2AccessCodeSecurity: t}
		}
	}
	return x
}

func NewSecurityRequirement(in interface{}) *SecurityRequirement {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewSecurityRequirement: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &SecurityRequirement{}
	// repeated NamedStringArray additional_properties = 1;
	// MAP: StringArray
	x.AdditionalProperties = make([]*NamedStringArray, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedStringArray{}
		pair.Name = k
		pair.Value = NewStringArray(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewStringArray(in interface{}) *StringArray {
	a, ok := in.([]interface{})
	if ok {
		x := &StringArray{}
		x.Value = make([]string, 0)
		for _, s := range a {
			x.Value = append(x.Value, s.(string))
		}
		return x
	} else {
		return nil
	}
}

func NewTag(in interface{}) *Tag {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewTag: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	requiredKeys := []string{"name"}
	if !helpers.MapContainsAllKeys(m, requiredKeys) {
		return nil
	}
	allowedKeys := []string{"description", "externalDocs", "name"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Tag{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string description = 2;
	if helpers.MapHasKey(m, "description") {
		x.Description = helpers.MapValueForKey(m, "description").(string)
	}
	// ExternalDocs external_docs = 3;
	if helpers.MapHasKey(m, "externalDocs") {
		x.ExternalDocs = NewExternalDocs(helpers.MapValueForKey(m, "externalDocs"))
	}
	// repeated NamedAny vendor_extension = 4;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}

func NewTypeItem(in interface{}) *TypeItem {
	value, ok := in.(string)
	x := &TypeItem{}
	if ok {
		x.Value = make([]string, 0)
		x.Value = append(x.Value, value)
	} else {
		log.Printf("unexpected: %+v", in)
	}
	return x
}

func NewVendorExtension(in interface{}) *VendorExtension {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewVendorExtension: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	x := &VendorExtension{}
	// repeated NamedAny additional_properties = 1;
	// MAP: Any
	x.AdditionalProperties = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		pair := &NamedAny{}
		pair.Name = k
		pair.Value = NewAny(v)
		x.AdditionalProperties = append(x.AdditionalProperties, pair)
	}
	return x
}

func NewXml(in interface{}) *Xml {
	m, ok := helpers.UnpackMap(in)
	if !ok {
		log.Printf("unexpected argument to NewXml: %+v", in)
		log.Printf("%d\n", len(m))
		return nil
	}
	allowedKeys := []string{"attribute", "name", "namespace", "prefix", "wrapped"}
	allowedPatterns := []string{"^x-"}
	if !helpers.MapContainsOnlyKeysAndPatterns(m, allowedKeys, allowedPatterns) {
		return nil
	}
	x := &Xml{}
	// string name = 1;
	if helpers.MapHasKey(m, "name") {
		x.Name = helpers.MapValueForKey(m, "name").(string)
	}
	// string namespace = 2;
	if helpers.MapHasKey(m, "namespace") {
		x.Namespace = helpers.MapValueForKey(m, "namespace").(string)
	}
	// string prefix = 3;
	if helpers.MapHasKey(m, "prefix") {
		x.Prefix = helpers.MapValueForKey(m, "prefix").(string)
	}
	// bool attribute = 4;
	if helpers.MapHasKey(m, "attribute") {
		x.Attribute = helpers.MapValueForKey(m, "attribute").(bool)
	}
	// bool wrapped = 5;
	if helpers.MapHasKey(m, "wrapped") {
		x.Wrapped = helpers.MapValueForKey(m, "wrapped").(bool)
	}
	// repeated NamedAny vendor_extension = 6;
	// MAP: Any ^x-
	x.VendorExtension = make([]*NamedAny, 0)
	for _, item := range m {
		k := item.Key.(string)
		v := item.Value
		if helpers.PatternMatches("^x-", k) {
			pair := &NamedAny{}
			pair.Name = k
			pair.Value = NewAny(v)
			x.VendorExtension = append(x.VendorExtension, pair)
		}
	}
	return x
}
