// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery/discovery.proto

package discovery_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Annotations struct {
	Required             []string `protobuf:"bytes,1,rep,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Annotations) Reset()         { *m = Annotations{} }
func (m *Annotations) String() string { return proto.CompactTextString(m) }
func (*Annotations) ProtoMessage()    {}
func (*Annotations) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{0}
}

func (m *Annotations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Annotations.Unmarshal(m, b)
}
func (m *Annotations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Annotations.Marshal(b, m, deterministic)
}
func (m *Annotations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Annotations.Merge(m, src)
}
func (m *Annotations) XXX_Size() int {
	return xxx_messageInfo_Annotations.Size(m)
}
func (m *Annotations) XXX_DiscardUnknown() {
	xxx_messageInfo_Annotations.DiscardUnknown(m)
}

var xxx_messageInfo_Annotations proto.InternalMessageInfo

func (m *Annotations) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

type Any struct {
	Value                *any.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Yaml                 string   `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{1}
}

func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Any) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

type Auth struct {
	Oauth2               *Oauth2  `protobuf:"bytes,1,opt,name=oauth2,proto3" json:"oauth2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{2}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetOauth2() *Oauth2 {
	if m != nil {
		return m.Oauth2
	}
	return nil
}

type Document struct {
	Kind                         string      `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	DiscoveryVersion             string      `protobuf:"bytes,2,opt,name=discovery_version,json=discoveryVersion,proto3" json:"discovery_version,omitempty"`
	Id                           string      `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                         string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Version                      string      `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Revision                     string      `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	Title                        string      `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description                  string      `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Icons                        *Icons      `protobuf:"bytes,9,opt,name=icons,proto3" json:"icons,omitempty"`
	DocumentationLink            string      `protobuf:"bytes,10,opt,name=documentation_link,json=documentationLink,proto3" json:"documentation_link,omitempty"`
	Labels                       []string    `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	Protocol                     string      `protobuf:"bytes,12,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BaseUrl                      string      `protobuf:"bytes,13,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	BasePath                     string      `protobuf:"bytes,14,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	RootUrl                      string      `protobuf:"bytes,15,opt,name=root_url,json=rootUrl,proto3" json:"root_url,omitempty"`
	ServicePath                  string      `protobuf:"bytes,16,opt,name=service_path,json=servicePath,proto3" json:"service_path,omitempty"`
	BatchPath                    string      `protobuf:"bytes,17,opt,name=batch_path,json=batchPath,proto3" json:"batch_path,omitempty"`
	Parameters                   *Parameters `protobuf:"bytes,18,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Auth                         *Auth       `protobuf:"bytes,19,opt,name=auth,proto3" json:"auth,omitempty"`
	Features                     []string    `protobuf:"bytes,20,rep,name=features,proto3" json:"features,omitempty"`
	Schemas                      *Schemas    `protobuf:"bytes,21,opt,name=schemas,proto3" json:"schemas,omitempty"`
	Methods                      *Methods    `protobuf:"bytes,22,opt,name=methods,proto3" json:"methods,omitempty"`
	Resources                    *Resources  `protobuf:"bytes,23,opt,name=resources,proto3" json:"resources,omitempty"`
	Etag                         string      `protobuf:"bytes,24,opt,name=etag,proto3" json:"etag,omitempty"`
	OwnerDomain                  string      `protobuf:"bytes,25,opt,name=owner_domain,json=ownerDomain,proto3" json:"owner_domain,omitempty"`
	OwnerName                    string      `protobuf:"bytes,26,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	VersionModule                bool        `protobuf:"varint,27,opt,name=version_module,json=versionModule,proto3" json:"version_module,omitempty"`
	CanonicalName                string      `protobuf:"bytes,28,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	FullyEncodeReservedExpansion bool        `protobuf:"varint,29,opt,name=fully_encode_reserved_expansion,json=fullyEncodeReservedExpansion,proto3" json:"fully_encode_reserved_expansion,omitempty"`
	PackagePath                  string      `protobuf:"bytes,30,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	MtlsRootUrl                  string      `protobuf:"bytes,31,opt,name=mtls_root_url,json=mtlsRootUrl,proto3" json:"mtls_root_url,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}    `json:"-"`
	XXX_unrecognized             []byte      `json:"-"`
	XXX_sizecache                int32       `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{3}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Document) GetDiscoveryVersion() string {
	if m != nil {
		return m.DiscoveryVersion
	}
	return ""
}

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Document) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Document) GetIcons() *Icons {
	if m != nil {
		return m.Icons
	}
	return nil
}

func (m *Document) GetDocumentationLink() string {
	if m != nil {
		return m.DocumentationLink
	}
	return ""
}

func (m *Document) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Document) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Document) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Document) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *Document) GetRootUrl() string {
	if m != nil {
		return m.RootUrl
	}
	return ""
}

func (m *Document) GetServicePath() string {
	if m != nil {
		return m.ServicePath
	}
	return ""
}

func (m *Document) GetBatchPath() string {
	if m != nil {
		return m.BatchPath
	}
	return ""
}

func (m *Document) GetParameters() *Parameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Document) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Document) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *Document) GetSchemas() *Schemas {
	if m != nil {
		return m.Schemas
	}
	return nil
}

func (m *Document) GetMethods() *Methods {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Document) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Document) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Document) GetOwnerDomain() string {
	if m != nil {
		return m.OwnerDomain
	}
	return ""
}

func (m *Document) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Document) GetVersionModule() bool {
	if m != nil {
		return m.VersionModule
	}
	return false
}

func (m *Document) GetCanonicalName() string {
	if m != nil {
		return m.CanonicalName
	}
	return ""
}

func (m *Document) GetFullyEncodeReservedExpansion() bool {
	if m != nil {
		return m.FullyEncodeReservedExpansion
	}
	return false
}

func (m *Document) GetPackagePath() string {
	if m != nil {
		return m.PackagePath
	}
	return ""
}

func (m *Document) GetMtlsRootUrl() string {
	if m != nil {
		return m.MtlsRootUrl
	}
	return ""
}

// Icons that represent the API.
type Icons struct {
	X16                  string   `protobuf:"bytes,1,opt,name=x16,proto3" json:"x16,omitempty"`
	X32                  string   `protobuf:"bytes,2,opt,name=x32,proto3" json:"x32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Icons) Reset()         { *m = Icons{} }
func (m *Icons) String() string { return proto.CompactTextString(m) }
func (*Icons) ProtoMessage()    {}
func (*Icons) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{4}
}

func (m *Icons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Icons.Unmarshal(m, b)
}
func (m *Icons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Icons.Marshal(b, m, deterministic)
}
func (m *Icons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Icons.Merge(m, src)
}
func (m *Icons) XXX_Size() int {
	return xxx_messageInfo_Icons.Size(m)
}
func (m *Icons) XXX_DiscardUnknown() {
	xxx_messageInfo_Icons.DiscardUnknown(m)
}

var xxx_messageInfo_Icons proto.InternalMessageInfo

func (m *Icons) GetX16() string {
	if m != nil {
		return m.X16
	}
	return ""
}

func (m *Icons) GetX32() string {
	if m != nil {
		return m.X32
	}
	return ""
}

type MediaUpload struct {
	Accept               []string   `protobuf:"bytes,1,rep,name=accept,proto3" json:"accept,omitempty"`
	MaxSize              string     `protobuf:"bytes,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Protocols            *Protocols `protobuf:"bytes,3,opt,name=protocols,proto3" json:"protocols,omitempty"`
	SupportsSubscription bool       `protobuf:"varint,4,opt,name=supports_subscription,json=supportsSubscription,proto3" json:"supports_subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MediaUpload) Reset()         { *m = MediaUpload{} }
func (m *MediaUpload) String() string { return proto.CompactTextString(m) }
func (*MediaUpload) ProtoMessage()    {}
func (*MediaUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{5}
}

func (m *MediaUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaUpload.Unmarshal(m, b)
}
func (m *MediaUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaUpload.Marshal(b, m, deterministic)
}
func (m *MediaUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaUpload.Merge(m, src)
}
func (m *MediaUpload) XXX_Size() int {
	return xxx_messageInfo_MediaUpload.Size(m)
}
func (m *MediaUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaUpload.DiscardUnknown(m)
}

var xxx_messageInfo_MediaUpload proto.InternalMessageInfo

func (m *MediaUpload) GetAccept() []string {
	if m != nil {
		return m.Accept
	}
	return nil
}

func (m *MediaUpload) GetMaxSize() string {
	if m != nil {
		return m.MaxSize
	}
	return ""
}

func (m *MediaUpload) GetProtocols() *Protocols {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *MediaUpload) GetSupportsSubscription() bool {
	if m != nil {
		return m.SupportsSubscription
	}
	return false
}

type Method struct {
	Id                      string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                    string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	HttpMethod              string       `protobuf:"bytes,3,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Description             string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Parameters              *Parameters  `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ParameterOrder          []string     `protobuf:"bytes,6,rep,name=parameter_order,json=parameterOrder,proto3" json:"parameter_order,omitempty"`
	Request                 *Request     `protobuf:"bytes,7,opt,name=request,proto3" json:"request,omitempty"`
	Response                *Response    `protobuf:"bytes,8,opt,name=response,proto3" json:"response,omitempty"`
	Scopes                  []string     `protobuf:"bytes,9,rep,name=scopes,proto3" json:"scopes,omitempty"`
	SupportsMediaDownload   bool         `protobuf:"varint,10,opt,name=supports_media_download,json=supportsMediaDownload,proto3" json:"supports_media_download,omitempty"`
	SupportsMediaUpload     bool         `protobuf:"varint,11,opt,name=supports_media_upload,json=supportsMediaUpload,proto3" json:"supports_media_upload,omitempty"`
	UseMediaDownloadService bool         `protobuf:"varint,12,opt,name=use_media_download_service,json=useMediaDownloadService,proto3" json:"use_media_download_service,omitempty"`
	MediaUpload             *MediaUpload `protobuf:"bytes,13,opt,name=media_upload,json=mediaUpload,proto3" json:"media_upload,omitempty"`
	SupportsSubscription    bool         `protobuf:"varint,14,opt,name=supports_subscription,json=supportsSubscription,proto3" json:"supports_subscription,omitempty"`
	FlatPath                string       `protobuf:"bytes,15,opt,name=flat_path,json=flatPath,proto3" json:"flat_path,omitempty"`
	EtagRequired            bool         `protobuf:"varint,16,opt,name=etag_required,json=etagRequired,proto3" json:"etag_required,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{6}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Method) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Method) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func (m *Method) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Method) GetParameters() *Parameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Method) GetParameterOrder() []string {
	if m != nil {
		return m.ParameterOrder
	}
	return nil
}

func (m *Method) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Method) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Method) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Method) GetSupportsMediaDownload() bool {
	if m != nil {
		return m.SupportsMediaDownload
	}
	return false
}

func (m *Method) GetSupportsMediaUpload() bool {
	if m != nil {
		return m.SupportsMediaUpload
	}
	return false
}

func (m *Method) GetUseMediaDownloadService() bool {
	if m != nil {
		return m.UseMediaDownloadService
	}
	return false
}

func (m *Method) GetMediaUpload() *MediaUpload {
	if m != nil {
		return m.MediaUpload
	}
	return nil
}

func (m *Method) GetSupportsSubscription() bool {
	if m != nil {
		return m.SupportsSubscription
	}
	return false
}

func (m *Method) GetFlatPath() string {
	if m != nil {
		return m.FlatPath
	}
	return ""
}

func (m *Method) GetEtagRequired() bool {
	if m != nil {
		return m.EtagRequired
	}
	return false
}

type Methods struct {
	AdditionalProperties []*NamedMethod `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Methods) Reset()         { *m = Methods{} }
func (m *Methods) String() string { return proto.CompactTextString(m) }
func (*Methods) ProtoMessage()    {}
func (*Methods) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{7}
}

func (m *Methods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Methods.Unmarshal(m, b)
}
func (m *Methods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Methods.Marshal(b, m, deterministic)
}
func (m *Methods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Methods.Merge(m, src)
}
func (m *Methods) XXX_Size() int {
	return xxx_messageInfo_Methods.Size(m)
}
func (m *Methods) XXX_DiscardUnknown() {
	xxx_messageInfo_Methods.DiscardUnknown(m)
}

var xxx_messageInfo_Methods proto.InternalMessageInfo

func (m *Methods) GetAdditionalProperties() []*NamedMethod {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

// Automatically-generated message used to represent maps of Method as ordered (name,value) pairs.
type NamedMethod struct {
	// Map key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapped value
	Value                *Method  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedMethod) Reset()         { *m = NamedMethod{} }
func (m *NamedMethod) String() string { return proto.CompactTextString(m) }
func (*NamedMethod) ProtoMessage()    {}
func (*NamedMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{8}
}

func (m *NamedMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedMethod.Unmarshal(m, b)
}
func (m *NamedMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedMethod.Marshal(b, m, deterministic)
}
func (m *NamedMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedMethod.Merge(m, src)
}
func (m *NamedMethod) XXX_Size() int {
	return xxx_messageInfo_NamedMethod.Size(m)
}
func (m *NamedMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedMethod.DiscardUnknown(m)
}

var xxx_messageInfo_NamedMethod proto.InternalMessageInfo

func (m *NamedMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedMethod) GetValue() *Method {
	if m != nil {
		return m.Value
	}
	return nil
}

// Automatically-generated message used to represent maps of Parameter as ordered (name,value) pairs.
type NamedParameter struct {
	// Map key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapped value
	Value                *Parameter `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NamedParameter) Reset()         { *m = NamedParameter{} }
func (m *NamedParameter) String() string { return proto.CompactTextString(m) }
func (*NamedParameter) ProtoMessage()    {}
func (*NamedParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{9}
}

func (m *NamedParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedParameter.Unmarshal(m, b)
}
func (m *NamedParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedParameter.Marshal(b, m, deterministic)
}
func (m *NamedParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedParameter.Merge(m, src)
}
func (m *NamedParameter) XXX_Size() int {
	return xxx_messageInfo_NamedParameter.Size(m)
}
func (m *NamedParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedParameter.DiscardUnknown(m)
}

var xxx_messageInfo_NamedParameter proto.InternalMessageInfo

func (m *NamedParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedParameter) GetValue() *Parameter {
	if m != nil {
		return m.Value
	}
	return nil
}

// Automatically-generated message used to represent maps of Resource as ordered (name,value) pairs.
type NamedResource struct {
	// Map key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapped value
	Value                *Resource `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NamedResource) Reset()         { *m = NamedResource{} }
func (m *NamedResource) String() string { return proto.CompactTextString(m) }
func (*NamedResource) ProtoMessage()    {}
func (*NamedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{10}
}

func (m *NamedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedResource.Unmarshal(m, b)
}
func (m *NamedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedResource.Marshal(b, m, deterministic)
}
func (m *NamedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedResource.Merge(m, src)
}
func (m *NamedResource) XXX_Size() int {
	return xxx_messageInfo_NamedResource.Size(m)
}
func (m *NamedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedResource.DiscardUnknown(m)
}

var xxx_messageInfo_NamedResource proto.InternalMessageInfo

func (m *NamedResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedResource) GetValue() *Resource {
	if m != nil {
		return m.Value
	}
	return nil
}

// Automatically-generated message used to represent maps of Schema as ordered (name,value) pairs.
type NamedSchema struct {
	// Map key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapped value
	Value                *Schema  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedSchema) Reset()         { *m = NamedSchema{} }
func (m *NamedSchema) String() string { return proto.CompactTextString(m) }
func (*NamedSchema) ProtoMessage()    {}
func (*NamedSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{11}
}

func (m *NamedSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedSchema.Unmarshal(m, b)
}
func (m *NamedSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedSchema.Marshal(b, m, deterministic)
}
func (m *NamedSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedSchema.Merge(m, src)
}
func (m *NamedSchema) XXX_Size() int {
	return xxx_messageInfo_NamedSchema.Size(m)
}
func (m *NamedSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedSchema.DiscardUnknown(m)
}

var xxx_messageInfo_NamedSchema proto.InternalMessageInfo

func (m *NamedSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedSchema) GetValue() *Schema {
	if m != nil {
		return m.Value
	}
	return nil
}

// Automatically-generated message used to represent maps of Scope as ordered (name,value) pairs.
type NamedScope struct {
	// Map key
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Mapped value
	Value                *Scope   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedScope) Reset()         { *m = NamedScope{} }
func (m *NamedScope) String() string { return proto.CompactTextString(m) }
func (*NamedScope) ProtoMessage()    {}
func (*NamedScope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{12}
}

func (m *NamedScope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedScope.Unmarshal(m, b)
}
func (m *NamedScope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedScope.Marshal(b, m, deterministic)
}
func (m *NamedScope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedScope.Merge(m, src)
}
func (m *NamedScope) XXX_Size() int {
	return xxx_messageInfo_NamedScope.Size(m)
}
func (m *NamedScope) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedScope.DiscardUnknown(m)
}

var xxx_messageInfo_NamedScope proto.InternalMessageInfo

func (m *NamedScope) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedScope) GetValue() *Scope {
	if m != nil {
		return m.Value
	}
	return nil
}

type Oauth2 struct {
	Scopes               *Scopes  `protobuf:"bytes,1,opt,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Oauth2) Reset()         { *m = Oauth2{} }
func (m *Oauth2) String() string { return proto.CompactTextString(m) }
func (*Oauth2) ProtoMessage()    {}
func (*Oauth2) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{13}
}

func (m *Oauth2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oauth2.Unmarshal(m, b)
}
func (m *Oauth2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oauth2.Marshal(b, m, deterministic)
}
func (m *Oauth2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oauth2.Merge(m, src)
}
func (m *Oauth2) XXX_Size() int {
	return xxx_messageInfo_Oauth2.Size(m)
}
func (m *Oauth2) XXX_DiscardUnknown() {
	xxx_messageInfo_Oauth2.DiscardUnknown(m)
}

var xxx_messageInfo_Oauth2 proto.InternalMessageInfo

func (m *Oauth2) GetScopes() *Scopes {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type Parameter struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XRef                 string       `protobuf:"bytes,3,opt,name=_ref,json=Ref,proto3" json:"_ref,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Default              string       `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	Required             bool         `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Format               string       `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Pattern              string       `protobuf:"bytes,8,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Minimum              string       `protobuf:"bytes,9,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              string       `protobuf:"bytes,10,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Enum                 []string     `protobuf:"bytes,11,rep,name=enum,proto3" json:"enum,omitempty"`
	EnumDescriptions     []string     `protobuf:"bytes,12,rep,name=enum_descriptions,json=enumDescriptions,proto3" json:"enum_descriptions,omitempty"`
	Repeated             bool         `protobuf:"varint,13,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Location             string       `protobuf:"bytes,14,opt,name=location,proto3" json:"location,omitempty"`
	Properties           *Schemas     `protobuf:"bytes,15,opt,name=properties,proto3" json:"properties,omitempty"`
	AdditionalProperties *Schema      `protobuf:"bytes,16,opt,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	Items                *Schema      `protobuf:"bytes,17,opt,name=items,proto3" json:"items,omitempty"`
	Annotations          *Annotations `protobuf:"bytes,18,opt,name=annotations,proto3" json:"annotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{14}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Parameter) GetXRef() string {
	if m != nil {
		return m.XRef
	}
	return ""
}

func (m *Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Parameter) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *Parameter) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Parameter) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Parameter) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Parameter) GetMinimum() string {
	if m != nil {
		return m.Minimum
	}
	return ""
}

func (m *Parameter) GetMaximum() string {
	if m != nil {
		return m.Maximum
	}
	return ""
}

func (m *Parameter) GetEnum() []string {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *Parameter) GetEnumDescriptions() []string {
	if m != nil {
		return m.EnumDescriptions
	}
	return nil
}

func (m *Parameter) GetRepeated() bool {
	if m != nil {
		return m.Repeated
	}
	return false
}

func (m *Parameter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Parameter) GetProperties() *Schemas {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Parameter) GetAdditionalProperties() *Schema {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

func (m *Parameter) GetItems() *Schema {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Parameter) GetAnnotations() *Annotations {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type Parameters struct {
	AdditionalProperties []*NamedParameter `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Parameters) Reset()         { *m = Parameters{} }
func (m *Parameters) String() string { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()    {}
func (*Parameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{15}
}

func (m *Parameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameters.Unmarshal(m, b)
}
func (m *Parameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameters.Marshal(b, m, deterministic)
}
func (m *Parameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameters.Merge(m, src)
}
func (m *Parameters) XXX_Size() int {
	return xxx_messageInfo_Parameters.Size(m)
}
func (m *Parameters) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameters.DiscardUnknown(m)
}

var xxx_messageInfo_Parameters proto.InternalMessageInfo

func (m *Parameters) GetAdditionalProperties() []*NamedParameter {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

type Protocols struct {
	Simple               *Simple    `protobuf:"bytes,1,opt,name=simple,proto3" json:"simple,omitempty"`
	Resumable            *Resumable `protobuf:"bytes,2,opt,name=resumable,proto3" json:"resumable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Protocols) Reset()         { *m = Protocols{} }
func (m *Protocols) String() string { return proto.CompactTextString(m) }
func (*Protocols) ProtoMessage()    {}
func (*Protocols) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{16}
}

func (m *Protocols) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocols.Unmarshal(m, b)
}
func (m *Protocols) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocols.Marshal(b, m, deterministic)
}
func (m *Protocols) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocols.Merge(m, src)
}
func (m *Protocols) XXX_Size() int {
	return xxx_messageInfo_Protocols.Size(m)
}
func (m *Protocols) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocols.DiscardUnknown(m)
}

var xxx_messageInfo_Protocols proto.InternalMessageInfo

func (m *Protocols) GetSimple() *Simple {
	if m != nil {
		return m.Simple
	}
	return nil
}

func (m *Protocols) GetResumable() *Resumable {
	if m != nil {
		return m.Resumable
	}
	return nil
}

type Request struct {
	XRef                 string   `protobuf:"bytes,1,opt,name=_ref,json=Ref,proto3" json:"_ref,omitempty"`
	ParameterName        string   `protobuf:"bytes,2,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{17}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetXRef() string {
	if m != nil {
		return m.XRef
	}
	return ""
}

func (m *Request) GetParameterName() string {
	if m != nil {
		return m.ParameterName
	}
	return ""
}

type Resource struct {
	Methods              *Methods   `protobuf:"bytes,1,opt,name=methods,proto3" json:"methods,omitempty"`
	Resources            *Resources `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{18}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetMethods() *Methods {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Resource) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Resources struct {
	AdditionalProperties []*NamedResource `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{19}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetAdditionalProperties() []*NamedResource {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

type Response struct {
	XRef                 string   `protobuf:"bytes,1,opt,name=_ref,json=Ref,proto3" json:"_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{20}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetXRef() string {
	if m != nil {
		return m.XRef
	}
	return ""
}

type Resumable struct {
	Multipart            bool     `protobuf:"varint,1,opt,name=multipart,proto3" json:"multipart,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resumable) Reset()         { *m = Resumable{} }
func (m *Resumable) String() string { return proto.CompactTextString(m) }
func (*Resumable) ProtoMessage()    {}
func (*Resumable) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{21}
}

func (m *Resumable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resumable.Unmarshal(m, b)
}
func (m *Resumable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resumable.Marshal(b, m, deterministic)
}
func (m *Resumable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resumable.Merge(m, src)
}
func (m *Resumable) XXX_Size() int {
	return xxx_messageInfo_Resumable.Size(m)
}
func (m *Resumable) XXX_DiscardUnknown() {
	xxx_messageInfo_Resumable.DiscardUnknown(m)
}

var xxx_messageInfo_Resumable proto.InternalMessageInfo

func (m *Resumable) GetMultipart() bool {
	if m != nil {
		return m.Multipart
	}
	return false
}

func (m *Resumable) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Schema struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Default              string       `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Required             bool         `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Format               string       `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Pattern              string       `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Minimum              string       `protobuf:"bytes,8,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              string       `protobuf:"bytes,9,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Enum                 []string     `protobuf:"bytes,10,rep,name=enum,proto3" json:"enum,omitempty"`
	EnumDescriptions     []string     `protobuf:"bytes,11,rep,name=enum_descriptions,json=enumDescriptions,proto3" json:"enum_descriptions,omitempty"`
	Repeated             bool         `protobuf:"varint,12,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Location             string       `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"`
	Properties           *Schemas     `protobuf:"bytes,14,opt,name=properties,proto3" json:"properties,omitempty"`
	AdditionalProperties *Schema      `protobuf:"bytes,15,opt,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	Items                *Schema      `protobuf:"bytes,16,opt,name=items,proto3" json:"items,omitempty"`
	XRef                 string       `protobuf:"bytes,17,opt,name=_ref,json=Ref,proto3" json:"_ref,omitempty"`
	Annotations          *Annotations `protobuf:"bytes,18,opt,name=annotations,proto3" json:"annotations,omitempty"`
	ReadOnly             bool         `protobuf:"varint,19,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{22}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Schema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Schema) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *Schema) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Schema) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Schema) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Schema) GetMinimum() string {
	if m != nil {
		return m.Minimum
	}
	return ""
}

func (m *Schema) GetMaximum() string {
	if m != nil {
		return m.Maximum
	}
	return ""
}

func (m *Schema) GetEnum() []string {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *Schema) GetEnumDescriptions() []string {
	if m != nil {
		return m.EnumDescriptions
	}
	return nil
}

func (m *Schema) GetRepeated() bool {
	if m != nil {
		return m.Repeated
	}
	return false
}

func (m *Schema) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Schema) GetProperties() *Schemas {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema) GetAdditionalProperties() *Schema {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

func (m *Schema) GetItems() *Schema {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Schema) GetXRef() string {
	if m != nil {
		return m.XRef
	}
	return ""
}

func (m *Schema) GetAnnotations() *Annotations {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Schema) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type Schemas struct {
	AdditionalProperties []*NamedSchema `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Schemas) Reset()         { *m = Schemas{} }
func (m *Schemas) String() string { return proto.CompactTextString(m) }
func (*Schemas) ProtoMessage()    {}
func (*Schemas) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{23}
}

func (m *Schemas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schemas.Unmarshal(m, b)
}
func (m *Schemas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schemas.Marshal(b, m, deterministic)
}
func (m *Schemas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schemas.Merge(m, src)
}
func (m *Schemas) XXX_Size() int {
	return xxx_messageInfo_Schemas.Size(m)
}
func (m *Schemas) XXX_DiscardUnknown() {
	xxx_messageInfo_Schemas.DiscardUnknown(m)
}

var xxx_messageInfo_Schemas proto.InternalMessageInfo

func (m *Schemas) GetAdditionalProperties() []*NamedSchema {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

type Scope struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scope) Reset()         { *m = Scope{} }
func (m *Scope) String() string { return proto.CompactTextString(m) }
func (*Scope) ProtoMessage()    {}
func (*Scope) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{24}
}

func (m *Scope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scope.Unmarshal(m, b)
}
func (m *Scope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scope.Marshal(b, m, deterministic)
}
func (m *Scope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scope.Merge(m, src)
}
func (m *Scope) XXX_Size() int {
	return xxx_messageInfo_Scope.Size(m)
}
func (m *Scope) XXX_DiscardUnknown() {
	xxx_messageInfo_Scope.DiscardUnknown(m)
}

var xxx_messageInfo_Scope proto.InternalMessageInfo

func (m *Scope) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Scopes struct {
	AdditionalProperties []*NamedScope `protobuf:"bytes,1,rep,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Scopes) Reset()         { *m = Scopes{} }
func (m *Scopes) String() string { return proto.CompactTextString(m) }
func (*Scopes) ProtoMessage()    {}
func (*Scopes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{25}
}

func (m *Scopes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scopes.Unmarshal(m, b)
}
func (m *Scopes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scopes.Marshal(b, m, deterministic)
}
func (m *Scopes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scopes.Merge(m, src)
}
func (m *Scopes) XXX_Size() int {
	return xxx_messageInfo_Scopes.Size(m)
}
func (m *Scopes) XXX_DiscardUnknown() {
	xxx_messageInfo_Scopes.DiscardUnknown(m)
}

var xxx_messageInfo_Scopes proto.InternalMessageInfo

func (m *Scopes) GetAdditionalProperties() []*NamedScope {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

type Simple struct {
	Multipart            bool     `protobuf:"varint,1,opt,name=multipart,proto3" json:"multipart,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Simple) Reset()         { *m = Simple{} }
func (m *Simple) String() string { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()    {}
func (*Simple) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{26}
}

func (m *Simple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Simple.Unmarshal(m, b)
}
func (m *Simple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Simple.Marshal(b, m, deterministic)
}
func (m *Simple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Simple.Merge(m, src)
}
func (m *Simple) XXX_Size() int {
	return xxx_messageInfo_Simple.Size(m)
}
func (m *Simple) XXX_DiscardUnknown() {
	xxx_messageInfo_Simple.DiscardUnknown(m)
}

var xxx_messageInfo_Simple proto.InternalMessageInfo

func (m *Simple) GetMultipart() bool {
	if m != nil {
		return m.Multipart
	}
	return false
}

func (m *Simple) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type StringArray struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec68c2b2e63f812, []int{27}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Annotations)(nil), "discovery.v1.Annotations")
	proto.RegisterType((*Any)(nil), "discovery.v1.Any")
	proto.RegisterType((*Auth)(nil), "discovery.v1.Auth")
	proto.RegisterType((*Document)(nil), "discovery.v1.Document")
	proto.RegisterType((*Icons)(nil), "discovery.v1.Icons")
	proto.RegisterType((*MediaUpload)(nil), "discovery.v1.MediaUpload")
	proto.RegisterType((*Method)(nil), "discovery.v1.Method")
	proto.RegisterType((*Methods)(nil), "discovery.v1.Methods")
	proto.RegisterType((*NamedMethod)(nil), "discovery.v1.NamedMethod")
	proto.RegisterType((*NamedParameter)(nil), "discovery.v1.NamedParameter")
	proto.RegisterType((*NamedResource)(nil), "discovery.v1.NamedResource")
	proto.RegisterType((*NamedSchema)(nil), "discovery.v1.NamedSchema")
	proto.RegisterType((*NamedScope)(nil), "discovery.v1.NamedScope")
	proto.RegisterType((*Oauth2)(nil), "discovery.v1.Oauth2")
	proto.RegisterType((*Parameter)(nil), "discovery.v1.Parameter")
	proto.RegisterType((*Parameters)(nil), "discovery.v1.Parameters")
	proto.RegisterType((*Protocols)(nil), "discovery.v1.Protocols")
	proto.RegisterType((*Request)(nil), "discovery.v1.Request")
	proto.RegisterType((*Resource)(nil), "discovery.v1.Resource")
	proto.RegisterType((*Resources)(nil), "discovery.v1.Resources")
	proto.RegisterType((*Response)(nil), "discovery.v1.Response")
	proto.RegisterType((*Resumable)(nil), "discovery.v1.Resumable")
	proto.RegisterType((*Schema)(nil), "discovery.v1.Schema")
	proto.RegisterType((*Schemas)(nil), "discovery.v1.Schemas")
	proto.RegisterType((*Scope)(nil), "discovery.v1.Scope")
	proto.RegisterType((*Scopes)(nil), "discovery.v1.Scopes")
	proto.RegisterType((*Simple)(nil), "discovery.v1.Simple")
	proto.RegisterType((*StringArray)(nil), "discovery.v1.StringArray")
}

func init() {
	proto.RegisterFile("discovery/discovery.proto", fileDescriptor_fec68c2b2e63f812)
}

var fileDescriptor_fec68c2b2e63f812 = []byte{
	// 1700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x53, 0xdc, 0xc8,
	0x11, 0xaf, 0x85, 0xfd, 0xdb, 0xbb, 0x0b, 0xcb, 0xf0, 0x4f, 0x60, 0x1c, 0x13, 0x5d, 0x5d, 0x02,
	0xb9, 0x3b, 0x28, 0xe3, 0x9c, 0x2b, 0x95, 0x4b, 0x1e, 0x70, 0xe0, 0xc1, 0x95, 0x60, 0xb0, 0x28,
	0x27, 0x95, 0x87, 0x94, 0x6a, 0x90, 0x66, 0x59, 0x15, 0x92, 0x46, 0x19, 0x8d, 0x30, 0xeb, 0x8f,
	0x93, 0xe7, 0xe4, 0x83, 0xe4, 0x7b, 0xe4, 0x73, 0xa4, 0xae, 0xa6, 0x67, 0xa4, 0xd5, 0x82, 0x76,
	0x8d, 0xf1, 0x13, 0xd3, 0xfd, 0xeb, 0x6e, 0xcd, 0xf4, 0x74, 0xff, 0xa6, 0x17, 0xd8, 0xf2, 0x83,
	0xd4, 0xe3, 0xb7, 0x4c, 0x8c, 0x0f, 0x8b, 0xd5, 0x41, 0x22, 0xb8, 0xe4, 0xa4, 0x37, 0x51, 0xdc,
	0xbe, 0xdc, 0xde, 0xba, 0xe6, 0xfc, 0x3a, 0x64, 0x87, 0x88, 0x5d, 0x65, 0xc3, 0x43, 0x1a, 0x1b,
	0x43, 0x7b, 0x1f, 0xba, 0xc7, 0x71, 0xcc, 0x25, 0x95, 0x01, 0x8f, 0x53, 0xb2, 0x0d, 0x6d, 0xc1,
	0xfe, 0x99, 0x05, 0x82, 0xf9, 0x56, 0x6d, 0x77, 0x71, 0xaf, 0xe3, 0x14, 0xb2, 0x7d, 0x0a, 0x8b,
	0xc7, 0xf1, 0x98, 0xfc, 0x06, 0x1a, 0xb7, 0x34, 0xcc, 0x98, 0x55, 0xdb, 0xad, 0xed, 0x75, 0x8f,
	0xd6, 0x0e, 0x74, 0xf0, 0x83, 0x3c, 0xf8, 0xc1, 0x71, 0x3c, 0x76, 0xb4, 0x09, 0x21, 0x50, 0x1f,
	0xd3, 0x28, 0xb4, 0x16, 0x76, 0x6b, 0x7b, 0x1d, 0x07, 0xd7, 0xf6, 0x6f, 0xa1, 0x7e, 0x9c, 0xc9,
	0x11, 0xf9, 0x1e, 0x9a, 0x9c, 0x66, 0x72, 0x74, 0x54, 0x04, 0x2a, 0xef, 0xf9, 0xe0, 0x1c, 0x31,
	0xc7, 0xd8, 0xd8, 0xff, 0x6d, 0x43, 0xfb, 0x84, 0x7b, 0x59, 0xc4, 0x62, 0xa9, 0xc2, 0xde, 0x04,
	0xb1, 0x8f, 0x8e, 0x1d, 0x07, 0xd7, 0xe4, 0x3b, 0x58, 0x29, 0xfc, 0xdd, 0x5b, 0x26, 0xd2, 0x80,
	0xc7, 0xe6, 0xbb, 0x83, 0x02, 0xf8, 0xab, 0xd6, 0x93, 0x25, 0x58, 0x08, 0x7c, 0x6b, 0x11, 0xd1,
	0x85, 0xc0, 0x57, 0x01, 0x63, 0x1a, 0x31, 0xab, 0xae, 0x03, 0xaa, 0x35, 0xb1, 0xa0, 0x95, 0x87,
	0x69, 0xa0, 0x3a, 0x17, 0x75, 0x92, 0x6e, 0x03, 0x84, 0x9a, 0x08, 0x15, 0x32, 0x59, 0x83, 0x86,
	0x0c, 0x64, 0xc8, 0xac, 0x16, 0x02, 0x5a, 0x20, 0xbb, 0xd0, 0xf5, 0x59, 0xea, 0x89, 0x20, 0x51,
	0x69, 0xb6, 0xda, 0x88, 0x95, 0x55, 0x64, 0x1f, 0x1a, 0x81, 0xc7, 0xe3, 0xd4, 0xea, 0x60, 0x32,
	0x56, 0xa7, 0x93, 0xf1, 0x56, 0x41, 0x8e, 0xb6, 0x20, 0x3f, 0x00, 0xf1, 0x4d, 0x26, 0xf0, 0xd6,
	0xdc, 0x30, 0x88, 0x6f, 0x2c, 0xc0, 0x98, 0x2b, 0x53, 0xc8, 0x5f, 0x82, 0xf8, 0x86, 0x6c, 0x40,
	0x33, 0xa4, 0x57, 0x2c, 0x4c, 0xad, 0x2e, 0x5e, 0xa8, 0x91, 0xd4, 0x29, 0xf0, 0xca, 0x3c, 0x1e,
	0x5a, 0x3d, 0x7d, 0x8a, 0x5c, 0x26, 0x5b, 0xd0, 0xbe, 0xa2, 0x29, 0x73, 0x33, 0x11, 0x5a, 0x7d,
	0x7d, 0x78, 0x25, 0x7f, 0x10, 0x21, 0x79, 0x06, 0x1d, 0x84, 0x12, 0x2a, 0x47, 0xd6, 0x92, 0xf6,
	0x53, 0x8a, 0x0b, 0x2a, 0x47, 0xca, 0x4f, 0x70, 0x2e, 0xd1, 0x6f, 0x59, 0xfb, 0x29, 0x59, 0xf9,
	0xfd, 0x12, 0x7a, 0x29, 0x13, 0xb7, 0x81, 0x67, 0x5c, 0x07, 0x3a, 0x07, 0x46, 0x87, 0xde, 0xcf,
	0x01, 0xae, 0xa8, 0xf4, 0x46, 0xda, 0x60, 0x05, 0x0d, 0x3a, 0xa8, 0x41, 0xf8, 0x77, 0x00, 0x09,
	0x15, 0x34, 0x62, 0x92, 0x89, 0xd4, 0x22, 0x98, 0x27, 0x6b, 0x3a, 0x4f, 0x17, 0x05, 0xee, 0x94,
	0x6c, 0xc9, 0xaf, 0xa0, 0xae, 0xaa, 0xc8, 0x5a, 0x45, 0x1f, 0x32, 0xed, 0xa3, 0x8a, 0xd1, 0x41,
	0x5c, 0xa5, 0x64, 0xc8, 0xa8, 0xcc, 0x04, 0x4b, 0xad, 0x35, 0x5d, 0xfd, 0xb9, 0x4c, 0x0e, 0xa1,
	0x95, 0x7a, 0x23, 0x16, 0xd1, 0xd4, 0x5a, 0xc7, 0x30, 0xeb, 0xd3, 0x61, 0x2e, 0x35, 0xe8, 0xe4,
	0x56, 0xca, 0x21, 0x62, 0x72, 0xc4, 0xfd, 0xd4, 0xda, 0xa8, 0x72, 0x38, 0xd3, 0xa0, 0x93, 0x5b,
	0x91, 0x1f, 0xa1, 0x23, 0x58, 0xca, 0x33, 0xe1, 0xb1, 0xd4, 0xda, 0x44, 0x97, 0xcd, 0x69, 0x17,
	0x27, 0x87, 0x9d, 0x89, 0xa5, 0xaa, 0x5d, 0x26, 0xe9, 0xb5, 0x65, 0xe9, 0xda, 0x55, 0x6b, 0x95,
	0x6c, 0xfe, 0x31, 0x66, 0xc2, 0xf5, 0x79, 0x44, 0x83, 0xd8, 0xda, 0xd2, 0xc9, 0x46, 0xdd, 0x09,
	0xaa, 0x54, 0xb2, 0xb5, 0x09, 0x16, 0xfe, 0xb6, 0x4e, 0x36, 0x6a, 0xde, 0xa9, 0xea, 0xff, 0x16,
	0x96, 0x4c, 0xb9, 0xbb, 0x11, 0xf7, 0xb3, 0x90, 0x59, 0xcf, 0x76, 0x6b, 0x7b, 0x6d, 0xa7, 0x6f,
	0xb4, 0x67, 0xa8, 0x54, 0x66, 0x1e, 0x8d, 0x79, 0x1c, 0x78, 0x34, 0xd4, 0x91, 0x76, 0x30, 0x52,
	0xbf, 0xd0, 0x62, 0xb4, 0x53, 0x78, 0x31, 0xcc, 0xc2, 0x70, 0xec, 0xb2, 0xd8, 0xe3, 0x3e, 0x73,
	0x05, 0x53, 0xf7, 0xce, 0x7c, 0x97, 0xdd, 0x25, 0x34, 0xc6, 0x46, 0x7a, 0x8e, 0xe1, 0x77, 0xd0,
	0xec, 0x14, 0xad, 0x1c, 0x63, 0x74, 0x9a, 0xdb, 0xa8, 0x63, 0x25, 0xd4, 0xbb, 0xa1, 0xd7, 0xa6,
	0x86, 0x7e, 0xa1, 0x8f, 0x65, 0x74, 0x58, 0x24, 0x36, 0xf4, 0x23, 0x19, 0xa6, 0x6e, 0x51, 0x86,
	0x2f, 0xb4, 0x8d, 0x52, 0x3a, 0xba, 0x14, 0xed, 0xef, 0xa0, 0x81, 0x0d, 0x45, 0x06, 0xb0, 0x78,
	0xf7, 0xf2, 0xb5, 0xa1, 0x11, 0xb5, 0x44, 0xcd, 0xab, 0x23, 0xc3, 0x1b, 0x6a, 0x69, 0xff, 0xbb,
	0x06, 0xdd, 0x33, 0xe6, 0x07, 0xf4, 0x43, 0x12, 0x72, 0xea, 0xab, 0x76, 0xa2, 0x9e, 0xc7, 0x12,
	0x69, 0xf8, 0xd1, 0x48, 0xaa, 0xf4, 0x23, 0x7a, 0xe7, 0xa6, 0xc1, 0x27, 0x66, 0xdc, 0x5b, 0x11,
	0xbd, 0xbb, 0x0c, 0x3e, 0x31, 0x75, 0xb1, 0x79, 0x67, 0xa5, 0x48, 0x3a, 0x0f, 0x2e, 0xf6, 0x22,
	0x87, 0x9d, 0x89, 0x25, 0x79, 0x05, 0xeb, 0x69, 0x96, 0x24, 0x5c, 0xc8, 0xd4, 0x4d, 0xb3, 0xab,
	0x09, 0x7d, 0xd4, 0x31, 0x55, 0x6b, 0x39, 0x78, 0x59, 0xc2, 0xec, 0xff, 0x34, 0xa0, 0xa9, 0x2b,
	0xcb, 0x90, 0x5c, 0xad, 0x4c, 0x72, 0x98, 0x35, 0x43, 0xc6, 0x6a, 0x4d, 0x5e, 0x40, 0x77, 0x24,
	0x65, 0xe2, 0xea, 0x1a, 0x34, 0x8c, 0x08, 0x4a, 0x65, 0x82, 0xdc, 0x63, 0xae, 0xfa, 0x43, 0xe6,
	0x9a, 0x6e, 0xcb, 0xc6, 0x17, 0xb4, 0xe5, 0xaf, 0x61, 0xb9, 0x90, 0x5c, 0x2e, 0x7c, 0x26, 0xac,
	0x26, 0xe6, 0x74, 0xa9, 0x50, 0x9f, 0x2b, 0xad, 0x6a, 0x25, 0xf5, 0x0a, 0xb1, 0x54, 0x22, 0xad,
	0x3e, 0x68, 0x25, 0x47, 0x83, 0x4e, 0x6e, 0x45, 0x8e, 0x14, 0x43, 0xa7, 0x09, 0x8f, 0x53, 0x86,
	0x64, 0xdb, 0x3d, 0xda, 0x78, 0xd0, 0x49, 0x88, 0x3a, 0x85, 0x9d, 0xba, 0xd8, 0xd4, 0xe3, 0x09,
	0x53, 0x14, 0x8c, 0x17, 0xab, 0x25, 0xf2, 0x1a, 0x36, 0x8b, 0x6b, 0x88, 0x54, 0x21, 0xb8, 0x3e,
	0xff, 0x18, 0xab, 0x5a, 0x40, 0xce, 0x6d, 0x3b, 0xc5, 0x2d, 0x61, 0x99, 0x9c, 0x18, 0x90, 0x1c,
	0x95, 0xae, 0x4f, 0xfb, 0x65, 0x58, 0x41, 0x56, 0x17, 0xbd, 0x56, 0xa7, 0xbc, 0x4c, 0x71, 0xfd,
	0x04, 0xdb, 0x59, 0xca, 0xee, 0x7d, 0xc6, 0x35, 0x1c, 0x89, 0x2c, 0xdd, 0x76, 0x36, 0xb3, 0x94,
	0x4d, 0x7d, 0xe9, 0x52, 0xc3, 0xe4, 0x0f, 0xd0, 0x9b, 0xfa, 0x4e, 0x1f, 0x0f, 0xbe, 0x75, 0x9f,
	0x75, 0x8a, 0xaf, 0x39, 0xdd, 0xa8, 0xf4, 0xe9, 0x99, 0xd5, 0xb6, 0x34, 0xbb, 0xda, 0xd4, 0x63,
	0x30, 0x0c, 0xa9, 0xd4, 0xdd, 0xa8, 0x09, 0xbf, 0xad, 0x14, 0xd8, 0x8a, 0xdf, 0x40, 0x5f, 0x91,
	0x91, 0x5b, 0x0c, 0x14, 0x03, 0x8c, 0xd4, 0x53, 0x4a, 0x27, 0x1f, 0x2a, 0xfe, 0x0e, 0x2d, 0x43,
	0x84, 0xe4, 0x1d, 0xac, 0x53, 0xdf, 0x0f, 0x54, 0x60, 0x1a, 0xba, 0x89, 0xe0, 0x09, 0x13, 0x32,
	0x60, 0x29, 0x36, 0xda, 0x83, 0x83, 0x28, 0x5e, 0xf1, 0xb5, 0xab, 0xb3, 0x36, 0xf1, 0xbb, 0x28,
	0xdc, 0xec, 0x33, 0xe8, 0x96, 0x8c, 0x8a, 0x37, 0xbe, 0x56, 0x7a, 0xe3, 0x8b, 0x59, 0x66, 0xa1,
	0x6a, 0x04, 0x31, 0xd1, 0xb5, 0x89, 0x7d, 0x09, 0x4b, 0x18, 0xae, 0x28, 0xe6, 0xca, 0x88, 0x3f,
	0x4c, 0x47, 0xdc, 0x9c, 0xd1, 0x08, 0x79, 0xd0, 0xf7, 0xd0, 0xc7, 0xa0, 0x39, 0xb3, 0x57, 0xc6,
	0xfc, 0x7e, 0x3a, 0xe6, 0x46, 0xf5, 0xa3, 0x90, 0x87, 0xcc, 0x8f, 0xad, 0x1f, 0xa4, 0x27, 0x1c,
	0x5b, 0x3b, 0xe6, 0xe1, 0xfe, 0x0c, 0x60, 0xc2, 0xf1, 0xa4, 0x7a, 0x7b, 0xfb, 0xd3, 0xd1, 0x56,
	0xef, 0x47, 0xe3, 0x49, 0xb1, 0xb7, 0xd7, 0xd0, 0xd4, 0x73, 0x9d, 0x9a, 0xfe, 0x4c, 0xb7, 0xd5,
	0xaa, 0xf7, 0xa0, 0xb0, 0xbc, 0x07, 0xed, 0xff, 0xd5, 0xa1, 0x33, 0xc9, 0x7b, 0x05, 0xb1, 0xc9,
	0x71, 0x92, 0xd3, 0x2e, 0xae, 0xc9, 0x0a, 0xd4, 0x5d, 0xc1, 0x86, 0x86, 0xd1, 0x16, 0x1d, 0x36,
	0x7c, 0x04, 0x95, 0x59, 0xd0, 0xf2, 0xd9, 0x90, 0x66, 0xa1, 0xcc, 0x47, 0x3e, 0x23, 0x4e, 0xcd,
	0xc5, 0x4d, 0x2c, 0xe3, 0x42, 0x56, 0xc4, 0x31, 0xe4, 0x22, 0xa2, 0xd2, 0xcc, 0x7c, 0x46, 0x52,
	0xd1, 0x12, 0x2a, 0x25, 0x13, 0xf9, 0xc0, 0x97, 0x8b, 0x0a, 0x89, 0x82, 0x38, 0x88, 0xb2, 0x08,
	0xc7, 0x3d, 0xf5, 0x54, 0x68, 0x11, 0x11, 0x7a, 0x87, 0x08, 0x14, 0x8f, 0x08, 0x22, 0xea, 0x99,
	0x8f, 0xb3, 0xc8, 0x0c, 0x71, 0xb8, 0x56, 0x33, 0xaf, 0xfa, 0xeb, 0x96, 0xce, 0x90, 0x5a, 0x3d,
	0x34, 0x18, 0x28, 0xe0, 0xa4, 0xa4, 0xd7, 0x47, 0x48, 0x18, 0x95, 0x4c, 0x53, 0x03, 0x1e, 0x41,
	0xcb, 0x0a, 0x0b, 0xb9, 0x47, 0x8b, 0x7e, 0xef, 0x38, 0x85, 0x4c, 0x7e, 0x04, 0x28, 0xf5, 0xe2,
	0xf2, 0xbc, 0xd9, 0xa7, 0x64, 0x48, 0xde, 0xce, 0xea, 0xe6, 0xc1, 0x9c, 0x9a, 0xab, 0x6c, 0x64,
	0x55, 0xae, 0x81, 0x64, 0x51, 0x8a, 0x23, 0xe1, 0xcc, 0x72, 0x45, 0x13, 0xf2, 0x13, 0x74, 0xe9,
	0xe4, 0xf7, 0x8c, 0x99, 0x12, 0xef, 0x51, 0x47, 0xe9, 0x07, 0x8f, 0x53, 0xb6, 0xb6, 0x5d, 0x80,
	0xc9, 0x53, 0x45, 0xde, 0xcf, 0xe7, 0xa3, 0x9d, 0x0a, 0x3e, 0x9a, 0xf4, 0x77, 0x35, 0x25, 0x25,
	0xd0, 0x29, 0x9e, 0x7a, 0x6c, 0x81, 0x20, 0x4a, 0x42, 0x36, 0xa3, 0x05, 0x10, 0x73, 0x8c, 0x8d,
	0x99, 0x0e, 0xb3, 0x88, 0x5e, 0x85, 0x33, 0xc8, 0xc5, 0xc9, 0x61, 0x67, 0x62, 0x69, 0xff, 0x09,
	0x5a, 0xe6, 0x75, 0x2c, 0x5a, 0xa2, 0x36, 0x69, 0x89, 0x6f, 0x61, 0xf2, 0xd4, 0xea, 0xf1, 0x4d,
	0xf7, 0x50, 0xbf, 0xd0, 0xaa, 0x63, 0xd9, 0x02, 0xda, 0x05, 0x41, 0x95, 0xc6, 0xda, 0xda, 0x97,
	0x8f, 0xb5, 0x0b, 0x8f, 0x1d, 0x6b, 0xed, 0x7f, 0x40, 0xa7, 0xd0, 0x93, 0x8b, 0xf9, 0x57, 0xf1,
	0xac, 0xe2, 0x2a, 0x0a, 0x5a, 0xac, 0xbe, 0x89, 0xe7, 0x78, 0x24, 0xfd, 0xf2, 0x3f, 0x4c, 0x8c,
	0xfd, 0x47, 0xfc, 0xba, 0xce, 0x21, 0xd9, 0x81, 0x4e, 0x94, 0x85, 0x32, 0x48, 0xa8, 0x90, 0x68,
	0xd4, 0x76, 0x26, 0x8a, 0xaa, 0xb1, 0xca, 0xfe, 0x7f, 0x1d, 0x9a, 0x86, 0x7f, 0x1f, 0x43, 0x56,
	0xf7, 0x98, 0x69, 0x71, 0x2e, 0x33, 0xd5, 0x67, 0x33, 0x53, 0x63, 0x26, 0x33, 0x35, 0x67, 0x31,
	0x53, 0x6b, 0x26, 0x33, 0xb5, 0x67, 0x32, 0x53, 0xa7, 0x9a, 0x99, 0xe0, 0x73, 0xcc, 0xd4, 0x7d,
	0x04, 0x33, 0xf5, 0xe6, 0x30, 0x53, 0x7f, 0x2e, 0x33, 0x2d, 0x7d, 0x35, 0x33, 0x2d, 0x3f, 0x9d,
	0x99, 0x06, 0x9f, 0x67, 0xa6, 0xbc, 0xca, 0x56, 0x26, 0xed, 0xf7, 0x35, 0x64, 0xa5, 0x66, 0x2f,
	0xc1, 0xa8, 0xef, 0xf2, 0x38, 0x1c, 0xe3, 0x2f, 0x5b, 0x4c, 0x1b, 0xf5, 0xcf, 0xe3, 0x70, 0xac,
	0xc6, 0x2a, 0x73, 0xf4, 0xa7, 0x8c, 0x55, 0xf3, 0xce, 0x6c, 0xef, 0x43, 0x43, 0xcf, 0x02, 0xf7,
	0xaa, 0xb6, 0xf6, 0xa0, 0x6a, 0xed, 0xbf, 0xa9, 0x2e, 0xc0, 0x21, 0xfa, 0x6c, 0xfe, 0x26, 0xac,
	0xca, 0x4d, 0xa8, 0xc1, 0xa1, 0x7a, 0x0f, 0xbf, 0x87, 0xa6, 0xa6, 0xc7, 0x27, 0xf4, 0xe6, 0x37,
	0xd0, 0xbd, 0x94, 0x22, 0x88, 0xaf, 0x8f, 0x85, 0xa0, 0x63, 0xb2, 0x36, 0xf9, 0x77, 0x96, 0xaa,
	0x4e, 0x2d, 0xbc, 0xd9, 0x83, 0x01, 0x17, 0xd7, 0x07, 0xa5, 0xff, 0x28, 0xbd, 0x7c, 0xd3, 0x3b,
	0x4f, 0x58, 0x7c, 0x7c, 0xf1, 0x16, 0x19, 0xfc, 0xa2, 0xf6, 0xaf, 0x85, 0xc5, 0xf3, 0xe3, 0xcb,
	0xab, 0x26, 0xfe, 0x60, 0x7b, 0xf5, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x22, 0xef, 0xc2,
	0x8d, 0x13, 0x00, 0x00,
}
