// Copyright 2020 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: metrics/complexity.proto

package gnostic_metrics_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The complexity metric includes measurements of the complexity of an API.
type Complexity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation statistics.
	PathCount   int32 `protobuf:"varint,1,opt,name=path_count,json=pathCount,proto3" json:"path_count,omitempty"`
	GetCount    int32 `protobuf:"varint,2,opt,name=get_count,json=getCount,proto3" json:"get_count,omitempty"`
	PostCount   int32 `protobuf:"varint,3,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	PutCount    int32 `protobuf:"varint,4,opt,name=put_count,json=putCount,proto3" json:"put_count,omitempty"`
	DeleteCount int32 `protobuf:"varint,5,opt,name=delete_count,json=deleteCount,proto3" json:"delete_count,omitempty"`
	// Model statistics.
	SchemaCount         int32 `protobuf:"varint,6,opt,name=schema_count,json=schemaCount,proto3" json:"schema_count,omitempty"`
	SchemaPropertyCount int32 `protobuf:"varint,7,opt,name=schema_property_count,json=schemaPropertyCount,proto3" json:"schema_property_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Complexity) Reset() {
	*x = Complexity{}
	mi := &file_metrics_complexity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complexity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complexity) ProtoMessage() {}

func (x *Complexity) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_complexity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complexity.ProtoReflect.Descriptor instead.
func (*Complexity) Descriptor() ([]byte, []int) {
	return file_metrics_complexity_proto_rawDescGZIP(), []int{0}
}

func (x *Complexity) GetPathCount() int32 {
	if x != nil {
		return x.PathCount
	}
	return 0
}

func (x *Complexity) GetGetCount() int32 {
	if x != nil {
		return x.GetCount
	}
	return 0
}

func (x *Complexity) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *Complexity) GetPutCount() int32 {
	if x != nil {
		return x.PutCount
	}
	return 0
}

func (x *Complexity) GetDeleteCount() int32 {
	if x != nil {
		return x.DeleteCount
	}
	return 0
}

func (x *Complexity) GetSchemaCount() int32 {
	if x != nil {
		return x.SchemaCount
	}
	return 0
}

func (x *Complexity) GetSchemaPropertyCount() int32 {
	if x != nil {
		return x.SchemaPropertyCount
	}
	return 0
}

var File_metrics_complexity_proto protoreflect.FileDescriptor

const file_metrics_complexity_proto_rawDesc = "" +
	"\n" +
	"\x18metrics/complexity.proto\x12\x12gnostic.metrics.v1\"\xfe\x01\n" +
	"\n" +
	"Complexity\x12\x1d\n" +
	"\n" +
	"path_count\x18\x01 \x01(\x05R\tpathCount\x12\x1b\n" +
	"\tget_count\x18\x02 \x01(\x05R\bgetCount\x12\x1d\n" +
	"\n" +
	"post_count\x18\x03 \x01(\x05R\tpostCount\x12\x1b\n" +
	"\tput_count\x18\x04 \x01(\x05R\bputCount\x12!\n" +
	"\fdelete_count\x18\x05 \x01(\x05R\vdeleteCount\x12!\n" +
	"\fschema_count\x18\x06 \x01(\x05R\vschemaCount\x122\n" +
	"\x15schema_property_count\x18\a \x01(\x05R\x13schemaPropertyCountB\x1eZ\x1c./metrics;gnostic_metrics_v1b\x06proto3"

var (
	file_metrics_complexity_proto_rawDescOnce sync.Once
	file_metrics_complexity_proto_rawDescData []byte
)

func file_metrics_complexity_proto_rawDescGZIP() []byte {
	file_metrics_complexity_proto_rawDescOnce.Do(func() {
		file_metrics_complexity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_complexity_proto_rawDesc), len(file_metrics_complexity_proto_rawDesc)))
	})
	return file_metrics_complexity_proto_rawDescData
}

var file_metrics_complexity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_complexity_proto_goTypes = []any{
	(*Complexity)(nil), // 0: gnostic.metrics.v1.Complexity
}
var file_metrics_complexity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metrics_complexity_proto_init() }
func file_metrics_complexity_proto_init() {
	if File_metrics_complexity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_complexity_proto_rawDesc), len(file_metrics_complexity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_complexity_proto_goTypes,
		DependencyIndexes: file_metrics_complexity_proto_depIdxs,
		MessageInfos:      file_metrics_complexity_proto_msgTypes,
	}.Build()
	File_metrics_complexity_proto = out.File
	file_metrics_complexity_proto_goTypes = nil
	file_metrics_complexity_proto_depIdxs = nil
}
